
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione4;

import java_cup.runtime.*;
import java.util.ArrayList;
import esercitazione4.ast.IdNode;
import esercitazione4.ast.ExprOpNode;
import esercitazione4.ast.Constants.*;
import esercitazione4.ast.ArithOp.*;
import esercitazione4.ast.BoolOp.*;
import esercitazione4.ast.RelOp.*;
import esercitazione4.ast.FunCallNode;
import esercitazione4.ast.ProgramNode;
import esercitazione4.ast.DeclOpNode;
import esercitazione4.ast.DefDeclOp.DefDeclNode;
import esercitazione4.ast.ParDeclOp.*;
import esercitazione4.ast.BodyNode;
import esercitazione4.ast.StatOp.*;
import esercitazione4.ast.Type;
import esercitazione4.ast.VarDeclOp.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\113\000\002\002\010\000\002\002\004\000\002\023" +
    "\004\000\002\023\004\000\002\023\002\000\002\025\004" +
    "\000\002\025\002\000\002\022\006\000\002\031\005\000" +
    "\002\031\007\000\002\031\003\000\002\031\005\000\002" +
    "\015\003\000\002\015\003\000\002\017\003\000\002\017" +
    "\003\000\002\017\003\000\002\017\003\000\002\017\003" +
    "\000\002\016\003\000\002\016\003\000\002\016\003\000" +
    "\002\016\003\000\002\016\003\000\002\016\003\000\002" +
    "\021\011\000\002\021\010\000\002\024\005\000\002\024" +
    "\003\000\002\020\005\000\002\030\005\000\002\030\003" +
    "\000\002\027\003\000\002\027\004\000\002\014\004\000" +
    "\002\014\002\000\002\010\006\000\002\011\004\000\002" +
    "\011\002\000\002\007\005\000\002\007\005\000\002\007" +
    "\005\000\002\007\006\000\002\007\004\000\002\007\012" +
    "\000\002\007\010\000\002\007\010\000\002\007\005\000" +
    "\002\026\005\000\002\026\003\000\002\012\005\000\002" +
    "\012\003\000\002\013\006\000\002\013\005\000\002\006" +
    "\005\000\002\006\005\000\002\006\005\000\002\006\005" +
    "\000\002\006\004\000\002\006\004\000\002\006\003\000" +
    "\002\006\003\000\002\006\003\000\002\003\003\000\002" +
    "\003\003\000\002\003\003\000\002\003\003\000\002\004" +
    "\003\000\002\004\003\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\005\003\000" +
    "\002\005\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\004\021\005\001\002\000\004\002\216\001" +
    "\002\000\010\013\011\022\ufffd\061\006\001\002\000\010" +
    "\053\215\057\ufff7\060\110\001\002\000\004\057\210\001" +
    "\002\000\010\013\011\022\ufffd\061\006\001\002\000\004" +
    "\061\153\001\002\000\004\022\015\001\002\000\010\013" +
    "\011\022\ufffd\061\006\001\002\000\004\022\ufffe\001\002" +
    "\000\036\004\ufffb\007\ufffb\011\ufffb\023\ufffb\024\ufffb\025" +
    "\ufffb\026\ufffb\027\ufffb\030\ufffb\031\ufffb\033\ufffb\040\ufffb" +
    "\047\ufffb\061\ufffb\001\002\000\036\004\031\007\023\011" +
    "\026\023\uffdb\024\030\025\037\026\034\027\021\030\043" +
    "\031\017\033\036\040\025\047\042\061\033\001\002\000" +
    "\050\032\uffe9\033\uffe9\034\uffe9\035\uffe9\036\uffe9\037\uffe9" +
    "\041\uffe9\042\uffe9\043\uffe9\044\uffe9\045\uffe9\046\uffe9\050" +
    "\uffe9\053\uffe9\054\uffe9\055\uffe9\057\uffe9\063\uffe9\064\uffe9" +
    "\001\002\000\040\004\031\007\023\011\026\023\uffdb\024" +
    "\030\025\037\026\034\027\021\030\043\031\017\033\036" +
    "\040\025\047\042\052\uffdb\061\150\001\002\000\050\032" +
    "\uffeb\033\uffeb\034\uffeb\035\uffeb\036\uffeb\037\uffeb\041\uffeb" +
    "\042\uffeb\043\uffeb\044\uffeb\045\uffeb\046\uffeb\050\uffeb\053" +
    "\uffeb\054\uffeb\055\uffeb\057\uffeb\063\uffeb\064\uffeb\001\002" +
    "\000\050\032\uffc3\033\uffc3\034\uffc3\035\uffc3\036\uffc3\037" +
    "\uffc3\041\uffc3\042\uffc3\043\uffc3\044\uffc3\045\uffc3\046\uffc3" +
    "\050\uffc3\053\uffc3\054\uffc3\055\uffc3\057\uffc3\063\uffc3\064" +
    "\uffc3\001\002\000\004\047\142\001\002\000\004\023\141" +
    "\001\002\000\026\024\030\025\037\026\034\027\021\030" +
    "\043\031\017\033\036\040\025\047\042\061\046\001\002" +
    "\000\026\024\030\025\037\026\034\027\021\030\043\031" +
    "\017\033\036\040\025\047\042\061\046\001\002\000\042" +
    "\032\uffc4\033\uffc4\034\uffc4\035\uffc4\036\uffc4\037\uffc4\041" +
    "\uffc4\042\uffc4\043\uffc4\044\uffc4\045\uffc4\046\uffc4\054\uffc4" +
    "\055\135\063\uffc4\064\uffc4\001\002\000\050\032\uffee\033" +
    "\uffee\034\uffee\035\uffee\036\uffee\037\uffee\041\uffee\042\uffee" +
    "\043\uffee\044\uffee\045\uffee\046\uffee\050\uffee\053\uffee\054" +
    "\uffee\055\uffee\057\uffee\063\uffee\064\uffee\001\002\000\004" +
    "\047\122\001\002\000\044\032\060\033\053\034\066\035" +
    "\065\036\054\037\072\041\063\042\056\043\071\044\061" +
    "\045\057\046\070\050\uffce\054\120\055\uffce\063\uffce\064" +
    "\uffce\001\002\000\054\032\uffc5\033\uffc5\034\uffc5\035\uffc5" +
    "\036\uffc5\037\uffc5\041\uffc5\042\uffc5\043\uffc5\044\uffc5\045" +
    "\uffc5\046\uffc5\047\047\053\111\054\uffc5\056\uffd0\057\ufff7" +
    "\060\110\062\uffd0\063\uffc5\064\uffc5\001\002\000\050\032" +
    "\uffec\033\uffec\034\uffec\035\uffec\036\uffec\037\uffec\041\uffec" +
    "\042\uffec\043\uffec\044\uffec\045\uffec\046\uffec\050\uffec\053" +
    "\uffec\054\uffec\055\uffec\057\uffec\063\uffec\064\uffec\001\002" +
    "\000\040\004\ufffc\007\ufffc\011\ufffc\023\ufffc\024\ufffc\025" +
    "\ufffc\026\ufffc\027\ufffc\030\ufffc\031\ufffc\033\ufffc\040\ufffc" +
    "\047\ufffc\052\ufffc\061\ufffc\001\002\000\026\024\030\025" +
    "\037\026\034\027\021\030\043\031\017\033\036\040\025" +
    "\047\042\061\046\001\002\000\050\032\uffed\033\uffed\034" +
    "\uffed\035\uffed\036\uffed\037\uffed\041\uffed\042\uffed\043\uffed" +
    "\044\uffed\045\uffed\046\uffed\050\uffed\053\uffed\054\uffed\055" +
    "\uffed\057\uffed\063\uffed\064\uffed\001\002\000\006\063\103" +
    "\064\104\001\002\000\006\056\077\062\076\001\002\000" +
    "\026\024\030\025\037\026\034\027\021\030\043\031\017" +
    "\033\036\040\025\047\042\061\046\001\002\000\050\032" +
    "\uffea\033\uffea\034\uffea\035\uffea\036\uffea\037\uffea\041\uffea" +
    "\042\uffea\043\uffea\044\uffea\045\uffea\046\uffea\050\uffea\053" +
    "\uffea\054\uffea\055\uffea\057\uffea\063\uffea\064\uffea\001\002" +
    "\000\034\032\060\033\053\034\066\035\065\036\054\037" +
    "\072\041\063\042\056\043\071\044\061\045\057\046\070" +
    "\050\067\001\002\000\050\032\uffc4\033\uffc4\034\uffc4\035" +
    "\uffc4\036\uffc4\037\uffc4\041\uffc4\042\uffc4\043\uffc4\044\uffc4" +
    "\045\uffc4\046\uffc4\050\uffc4\053\uffc4\054\uffc4\055\uffc4\057" +
    "\uffc4\063\uffc4\064\uffc4\001\002\000\052\032\uffc5\033\uffc5" +
    "\034\uffc5\035\uffc5\036\uffc5\037\uffc5\041\uffc5\042\uffc5\043" +
    "\uffc5\044\uffc5\045\uffc5\046\uffc5\047\047\050\uffc5\053\uffc5" +
    "\054\uffc5\055\uffc5\057\uffc5\063\uffc5\064\uffc5\001\002\000" +
    "\030\024\030\025\037\026\034\027\021\030\043\031\017" +
    "\033\036\040\025\047\042\050\051\061\046\001\002\000" +
    "\004\050\052\001\002\000\050\032\uffcc\033\uffcc\034\uffcc" +
    "\035\uffcc\036\uffcc\037\uffcc\041\uffcc\042\uffcc\043\uffcc\044" +
    "\uffcc\045\uffcc\046\uffcc\050\uffcc\053\uffcc\054\uffcc\055\uffcc" +
    "\057\uffcc\063\uffcc\064\uffcc\001\002\000\050\032\uffcd\033" +
    "\uffcd\034\uffcd\035\uffcd\036\uffcd\037\uffcd\041\uffcd\042\uffcd" +
    "\043\uffcd\044\uffcd\045\uffcd\046\uffcd\050\uffcd\053\uffcd\054" +
    "\uffcd\055\uffcd\057\uffcd\063\uffcd\064\uffcd\001\002\000\026" +
    "\024\uffc1\025\uffc1\026\uffc1\027\uffc1\030\uffc1\031\uffc1\033" +
    "\uffc1\040\uffc1\047\uffc1\061\uffc1\001\002\000\026\024\uffbe" +
    "\025\uffbe\026\uffbe\027\uffbe\030\uffbe\031\uffbe\033\uffbe\040" +
    "\uffbe\047\uffbe\061\uffbe\001\002\000\026\024\030\025\037" +
    "\026\034\027\021\030\043\031\017\033\036\040\025\047" +
    "\042\061\046\001\002\000\026\024\uffbb\025\uffbb\026\uffbb" +
    "\027\uffbb\030\uffbb\031\uffbb\033\uffbb\040\uffbb\047\uffbb\061" +
    "\uffbb\001\002\000\026\024\uffb8\025\uffb8\026\uffb8\027\uffb8" +
    "\030\uffb8\031\uffb8\033\uffb8\040\uffb8\047\uffb8\061\uffb8\001" +
    "\002\000\026\024\uffc2\025\uffc2\026\uffc2\027\uffc2\030\uffc2" +
    "\031\uffc2\033\uffc2\040\uffc2\047\uffc2\061\uffc2\001\002\000" +
    "\026\024\uffb9\025\uffb9\026\uffb9\027\uffb9\030\uffb9\031\uffb9" +
    "\033\uffb9\040\uffb9\047\uffb9\061\uffb9\001\002\000\026\024" +
    "\030\025\037\026\034\027\021\030\043\031\017\033\036" +
    "\040\025\047\042\061\046\001\002\000\026\024\uffbc\025" +
    "\uffbc\026\uffbc\027\uffbc\030\uffbc\031\uffbc\033\uffbc\040\uffbc" +
    "\047\uffbc\061\uffbc\001\002\000\026\024\030\025\037\026" +
    "\034\027\021\030\043\031\017\033\036\040\025\047\042" +
    "\061\046\001\002\000\026\024\uffbf\025\uffbf\026\uffbf\027" +
    "\uffbf\030\uffbf\031\uffbf\033\uffbf\040\uffbf\047\uffbf\061\uffbf" +
    "\001\002\000\026\024\uffc0\025\uffc0\026\uffc0\027\uffc0\030" +
    "\uffc0\031\uffc0\033\uffc0\040\uffc0\047\uffc0\061\uffc0\001\002" +
    "\000\050\032\uffc8\033\uffc8\034\uffc8\035\uffc8\036\uffc8\037" +
    "\uffc8\041\uffc8\042\uffc8\043\uffc8\044\uffc8\045\uffc8\046\uffc8" +
    "\050\uffc8\053\uffc8\054\uffc8\055\uffc8\057\uffc8\063\uffc8\064" +
    "\uffc8\001\002\000\026\024\uffb7\025\uffb7\026\uffb7\027\uffb7" +
    "\030\uffb7\031\uffb7\033\uffb7\040\uffb7\047\uffb7\061\uffb7\001" +
    "\002\000\026\024\uffba\025\uffba\026\uffba\027\uffba\030\uffba" +
    "\031\uffba\033\uffba\040\uffba\047\uffba\061\uffba\001\002\000" +
    "\026\024\uffbd\025\uffbd\026\uffbd\027\uffbd\030\uffbd\031\uffbd" +
    "\033\uffbd\040\uffbd\047\uffbd\061\uffbd\001\002\000\050\032" +
    "\060\033\053\034\066\035\065\036\054\037\072\041\063" +
    "\042\056\043\071\044\061\045\057\046\070\050\uffc9\053" +
    "\uffc9\054\uffc9\055\uffc9\057\uffc9\063\uffc9\064\uffc9\001\002" +
    "\000\050\032\060\033\053\034\066\035\065\036\054\037" +
    "\072\041\063\042\056\043\071\044\061\045\057\046\070" +
    "\050\uffca\053\uffca\054\uffca\055\uffca\057\uffca\063\uffca\064" +
    "\uffca\001\002\000\050\032\060\033\053\034\066\035\065" +
    "\036\054\037\072\041\063\042\056\043\071\044\061\045" +
    "\057\046\070\050\uffcb\053\uffcb\054\uffcb\055\uffcb\057\uffcb" +
    "\063\uffcb\064\uffcb\001\002\000\004\055\102\001\002\000" +
    "\026\024\030\025\037\026\034\027\021\030\043\031\017" +
    "\033\036\040\025\047\042\061\046\001\002\000\004\055" +
    "\101\001\002\000\040\004\uffd7\007\uffd7\011\uffd7\023\uffd7" +
    "\024\uffd7\025\uffd7\026\uffd7\027\uffd7\030\uffd7\031\uffd7\033" +
    "\uffd7\040\uffd7\047\uffd7\052\uffd7\061\uffd7\001\002\000\040" +
    "\004\uffda\007\uffda\011\uffda\023\uffda\024\uffda\025\uffda\026" +
    "\uffda\027\uffda\030\uffda\031\uffda\033\uffda\040\uffda\047\uffda" +
    "\052\uffda\061\uffda\001\002\000\004\055\106\001\002\000" +
    "\004\055\105\001\002\000\040\004\uffd8\007\uffd8\011\uffd8" +
    "\023\uffd8\024\uffd8\025\uffd8\026\uffd8\027\uffd8\030\uffd8\031" +
    "\uffd8\033\uffd8\040\uffd8\047\uffd8\052\uffd8\061\uffd8\001\002" +
    "\000\040\004\uffd9\007\uffd9\011\uffd9\023\uffd9\024\uffd9\025" +
    "\uffd9\026\uffd9\027\uffd9\030\uffd9\031\uffd9\033\uffd9\040\uffd9" +
    "\047\uffd9\052\uffd9\061\uffd9\001\002\000\050\032\uffc7\033" +
    "\uffc7\034\066\035\065\036\uffc7\037\uffc7\041\uffc7\042\uffc7" +
    "\043\uffc7\044\uffc7\045\uffc7\046\uffc7\050\uffc7\053\uffc7\054" +
    "\uffc7\055\uffc7\057\uffc7\063\uffc7\064\uffc7\001\002\000\026" +
    "\024\030\025\037\026\034\027\021\030\043\031\017\033" +
    "\036\040\025\047\042\061\046\001\002\000\004\061\112" +
    "\001\002\000\014\053\111\056\uffd0\057\ufff7\060\110\062" +
    "\uffd0\001\002\000\004\057\ufff9\001\002\000\006\056\uffd1" +
    "\062\uffd1\001\002\000\036\032\060\033\053\034\066\035" +
    "\065\036\054\037\072\041\063\042\056\043\071\044\061" +
    "\045\057\046\070\053\116\057\ufff6\001\002\000\004\061" +
    "\006\001\002\000\004\057\ufff8\001\002\000\026\024\030" +
    "\025\037\026\034\027\021\030\043\031\017\033\036\040" +
    "\025\047\042\061\046\001\002\000\012\050\uffcf\055\uffcf" +
    "\063\uffcf\064\uffcf\001\002\000\026\024\030\025\037\026" +
    "\034\027\021\030\043\031\017\033\036\040\025\047\042" +
    "\061\046\001\002\000\034\032\060\033\053\034\066\035" +
    "\065\036\054\037\072\041\063\042\056\043\071\044\061" +
    "\045\057\046\070\050\124\001\002\000\004\005\125\001" +
    "\002\000\004\051\126\001\002\000\036\004\ufffb\007\ufffb" +
    "\011\ufffb\024\ufffb\025\ufffb\026\ufffb\027\ufffb\030\ufffb\031" +
    "\ufffb\033\ufffb\040\ufffb\047\ufffb\052\ufffb\061\ufffb\001\002" +
    "\000\042\004\uffd4\006\130\007\uffd4\011\uffd4\023\uffd4\024" +
    "\uffd4\025\uffd4\026\uffd4\027\uffd4\030\uffd4\031\uffd4\033\uffd4" +
    "\040\uffd4\047\uffd4\052\uffd4\061\uffd4\001\002\000\004\051" +
    "\126\001\002\000\040\004\uffd5\007\uffd5\011\uffd5\023\uffd5" +
    "\024\uffd5\025\uffd5\026\uffd5\027\uffd5\030\uffd5\031\uffd5\033" +
    "\uffd5\040\uffd5\047\uffd5\052\uffd5\061\uffd5\001\002\000\036" +
    "\004\031\007\023\011\026\024\030\025\037\026\034\027" +
    "\021\030\043\031\017\033\036\040\025\047\042\052\uffdb" +
    "\061\033\001\002\000\004\052\134\001\002\000\046\004" +
    "\uffdd\006\uffdd\007\uffdd\011\uffdd\013\uffdd\022\uffdd\023\uffdd" +
    "\024\uffdd\025\uffdd\026\uffdd\027\uffdd\030\uffdd\031\uffdd\033" +
    "\uffdd\040\uffdd\047\uffdd\052\uffdd\061\uffdd\001\002\000\040" +
    "\004\uffd6\007\uffd6\011\uffd6\023\uffd6\024\uffd6\025\uffd6\026" +
    "\uffd6\027\uffd6\030\uffd6\031\uffd6\033\uffd6\040\uffd6\047\uffd6" +
    "\052\uffd6\061\uffd6\001\002\000\034\032\060\033\053\034" +
    "\066\035\065\036\054\037\072\041\063\042\056\043\071" +
    "\044\061\045\057\046\070\055\137\001\002\000\040\004" +
    "\uffd2\007\uffd2\011\uffd2\023\uffd2\024\uffd2\025\uffd2\026\uffd2" +
    "\027\uffd2\030\uffd2\031\uffd2\033\uffd2\040\uffd2\047\uffd2\052" +
    "\uffd2\061\uffd2\001\002\000\050\032\060\033\053\034\066" +
    "\035\065\036\uffc6\037\uffc6\041\063\042\056\043\071\044" +
    "\061\045\057\046\070\050\uffc6\053\uffc6\054\uffc6\055\uffc6" +
    "\057\uffc6\063\uffc6\064\uffc6\001\002\000\004\002\001\001" +
    "\002\000\026\024\030\025\037\026\034\027\021\030\043" +
    "\031\017\033\036\040\025\047\042\061\046\001\002\000" +
    "\034\032\060\033\053\034\066\035\065\036\054\037\072" +
    "\041\063\042\056\043\071\044\061\045\057\046\070\050" +
    "\144\001\002\000\004\010\145\001\002\000\004\051\126" +
    "\001\002\000\040\004\uffd3\007\uffd3\011\uffd3\023\uffd3\024" +
    "\uffd3\025\uffd3\026\uffd3\027\uffd3\030\uffd3\031\uffd3\033\uffd3" +
    "\040\uffd3\047\uffd3\052\uffd3\061\uffd3\001\002\000\006\023" +
    "\uffdc\052\uffdc\001\002\000\050\032\uffc5\033\uffc5\034\uffc5" +
    "\035\uffc5\036\uffc5\037\uffc5\041\uffc5\042\uffc5\043\uffc5\044" +
    "\uffc5\045\uffc5\046\uffc5\047\047\053\151\054\uffc5\056\uffd0" +
    "\062\uffd0\063\uffc5\064\uffc5\001\002\000\004\061\152\001" +
    "\002\000\010\053\151\056\uffd0\062\uffd0\001\002\000\004" +
    "\047\154\001\002\000\010\012\160\050\162\061\155\001" +
    "\002\000\006\054\uffe1\057\uffe1\001\002\000\004\057\205" +
    "\001\002\000\006\054\203\057\uffe2\001\002\000\004\061" +
    "\202\001\002\000\004\050\177\001\002\000\006\051\uffde" +
    "\057\166\001\002\000\006\050\uffe5\055\164\001\002\000" +
    "\006\012\160\061\155\001\002\000\004\050\uffe6\001\002" +
    "\000\014\014\176\015\174\016\173\017\171\020\175\001" +
    "\002\000\004\051\126\001\002\000\010\013\uffe7\022\uffe7" +
    "\061\uffe7\001\002\000\010\050\ufff0\051\ufff0\055\ufff0\001" +
    "\002\000\004\051\uffdf\001\002\000\010\050\ufff1\051\ufff1" +
    "\055\ufff1\001\002\000\010\050\ufff2\051\ufff2\055\ufff2\001" +
    "\002\000\010\050\uffef\051\uffef\055\uffef\001\002\000\010" +
    "\050\ufff3\051\ufff3\055\ufff3\001\002\000\006\051\uffde\057" +
    "\166\001\002\000\004\051\126\001\002\000\010\013\uffe8" +
    "\022\uffe8\061\uffe8\001\002\000\006\054\uffe0\057\uffe0\001" +
    "\002\000\006\012\160\061\155\001\002\000\004\057\uffe3" +
    "\001\002\000\014\014\176\015\174\016\173\017\171\020" +
    "\175\001\002\000\006\050\uffe4\055\uffe4\001\002\000\004" +
    "\022\uffff\001\002\000\030\014\176\015\174\016\173\017" +
    "\171\020\175\024\030\025\037\026\034\027\021\030\043" +
    "\031\017\001\002\000\004\055\ufff5\001\002\000\004\055" +
    "\214\001\002\000\004\055\ufff4\001\002\000\044\004\ufffa" +
    "\007\ufffa\011\ufffa\013\ufffa\022\ufffa\023\ufffa\024\ufffa\025" +
    "\ufffa\026\ufffa\027\ufffa\030\ufffa\031\ufffa\033\ufffa\040\ufffa" +
    "\047\ufffa\052\ufffa\061\ufffa\001\002\000\004\061\006\001" +
    "\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\004\002\003\001\001\000\002\001\001\000" +
    "\012\021\012\022\007\023\011\031\006\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\021\012\022\007\023" +
    "\206\031\006\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\021\012\022\007\023\013\031\006\001\001\000" +
    "\002\001\001\000\004\025\015\001\001\000\024\006\031" +
    "\007\017\011\023\012\037\013\026\016\021\022\034\026" +
    "\040\031\006\001\001\000\002\001\001\000\020\006\031" +
    "\007\017\011\146\012\037\013\026\016\021\026\040\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\006\137\013\044\016\021\001" +
    "\001\000\010\006\135\013\044\016\021\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\003" +
    "\054\004\061\005\063\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\006\106\013\044\016" +
    "\021\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\006\043\013\044\016\021\001\001\000" +
    "\002\001\001\000\010\003\054\004\061\005\063\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\006\031\012" +
    "\047\013\044\016\021\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\006\074\013\044\016\021\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\006\073\013\044\016\021\001\001\000\002" +
    "\001\001\000\010\006\072\013\044\016\021\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\003" +
    "\054\004\061\005\063\001\001\000\010\003\054\004\061" +
    "\005\063\001\001\000\010\003\054\004\061\005\063\001" +
    "\001\000\002\001\001\000\012\006\031\012\077\013\044" +
    "\016\021\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\003\054\004\061\005" +
    "\063\001\001\000\010\006\114\013\044\016\021\001\001" +
    "\000\006\026\113\031\112\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\003\054\004\061" +
    "\005\063\001\001\000\004\031\116\001\001\000\002\001" +
    "\001\000\012\006\031\012\120\013\044\016\021\001\001" +
    "\000\002\001\001\000\010\006\122\013\044\016\021\001" +
    "\001\000\010\003\054\004\061\005\063\001\001\000\002" +
    "\001\001\000\004\010\126\001\001\000\004\025\131\001" +
    "\001\000\002\001\001\000\004\010\130\001\001\000\002" +
    "\001\001\000\024\006\031\007\017\011\132\012\037\013" +
    "\026\016\021\022\034\026\040\031\006\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\003" +
    "\054\004\061\005\063\001\001\000\002\001\001\000\010" +
    "\003\054\004\061\005\063\001\001\000\002\001\001\000" +
    "\010\006\142\013\044\016\021\001\001\000\010\003\054" +
    "\004\061\005\063\001\001\000\002\001\001\000\004\010" +
    "\145\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\026\113\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\020\162\024\160\027\156\030\155" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\166" +
    "\001\001\000\002\001\001\000\012\020\162\024\164\027" +
    "\156\030\155\001\001\000\002\001\001\000\004\017\171" +
    "\001\001\000\004\010\167\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\177\001\001\000\004\010\200\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\027\156\030\203\001\001\000" +
    "\002\001\001\000\004\017\205\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\015\211\016\212\017\210\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\031\112\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Programma ::= PROGRAM Decls BEGIN VarDecls Statements END 
            {
              Object RESULT =null;
		int declsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int declsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		ArrayList<DeclOpNode> decls = (ArrayList<DeclOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<VarDeclNode> vars = (ArrayList<VarDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int statsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int statsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<StatOpNode> stats = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ProgramNode(decls, vars, stats);
                                                                              System.out.println(RESULT);
                                                                           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Programma",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Programma EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Decls ::= VarDecl Decls 
            {
              ArrayList<DeclOpNode> RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object var = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<DeclOpNode> list = (ArrayList<DeclOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(0, (VarDeclNode) var);
                                    RESULT = list;
                                    System.out.println("VarDecls Fittizio: " + RESULT);
                                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Decls",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Decls ::= DefDecl Decls 
            {
              ArrayList<DeclOpNode> RESULT =null;
		int defleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int defright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object def = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<DeclOpNode> list = (ArrayList<DeclOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(0, (DefDeclNode) def);
                                  RESULT = list;
                                  System.out.println("DefDecls Fittizio: " + RESULT);
                               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Decls",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Decls ::= 
            {
              ArrayList<DeclOpNode> RESULT =null;
		 ArrayList<DeclOpNode> list = new ArrayList<>();
                       RESULT = list;
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Decls",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // VarDecls ::= VarDecls VarDecl 
            {
              ArrayList<VarDeclNode> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<VarDeclNode> list = (ArrayList<VarDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object var = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((VarDeclNode) var);
                                          RESULT = list;
                                          //System.out.println("VarDecls Fittizio: " + RESULT);
                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarDecls",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // VarDecls ::= 
            {
              ArrayList<VarDeclNode> RESULT =null;
		 ArrayList<VarDeclNode> list = new ArrayList<>();
                         RESULT = list;
                      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarDecls",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // VarDecl ::= VarsOptInit COLON TypeOrConstant SEMI 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<VarOptInitNode> vars = (ArrayList<VarOptInitNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int typeOrConstantleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeOrConstantright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object typeOrConstant = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new VarDeclNode(vars, typeOrConstant); System.out.println(RESULT);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarDecl",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // VarsOptInit ::= ID PIPE VarsOptInit 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<VarOptInitNode> list = (ArrayList<VarOptInitNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(new VarOptInitNode(new IdNode(attrib)));
                                                   RESULT = list;
                                                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // VarsOptInit ::= ID ASSIGNDECL Expr PIPE VarsOptInit 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<VarOptInitNode> list = (ArrayList<VarOptInitNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(new VarOptInitNode(new IdNode(id), expr));
                                                                  RESULT = list;
                                                                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // VarsOptInit ::= ID 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<VarOptInitNode> list = new ArrayList<>();
                           list.add(new VarOptInitNode(new IdNode(attrib)));
                           RESULT = list;
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // VarsOptInit ::= ID ASSIGNDECL Expr 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<VarOptInitNode> list = new ArrayList<>();
                                            list.add(new VarOptInitNode(new IdNode(id), expr));
                                            RESULT = list;
                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // TypeOrConstant ::= Type 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib;  System.out.println("Type Fittizio: " + RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TypeOrConstant",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // TypeOrConstant ::= Constant 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib; System.out.println("Constant Fittizio: " + RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TypeOrConstant",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Type ::= INT 
            {
              Object RESULT =null;
		 RESULT = Type.INT; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Type ::= BOOL 
            {
              Object RESULT =null;
		 RESULT = Type.BOOL; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Type ::= DOUBLE 
            {
              Object RESULT =null;
		 RESULT = Type.DOUBLE; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Type ::= STRING 
            {
              Object RESULT =null;
		 RESULT = Type.STRING; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Type ::= CHAR 
            {
              Object RESULT =null;
		 RESULT = Type.CHAR; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Constant ::= TRUE 
            {
              Object RESULT =null;
		 RESULT = new BoolNode(true); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Constant ::= FALSE 
            {
              Object RESULT =null;
		 RESULT = new BoolNode(false); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Constant ::= INT_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IntNode((int) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Constant ::= DOUBLE_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DoubleNode((double) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Constant ::= CHAR_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CharNode((char) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Constant ::= STRING_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new StringNode((String) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // DefDecl ::= DEF ID LPAR ParDecls RPAR OptType Body 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<ParDeclNode> params = (ArrayList<ParDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DefDeclNode(new IdNode(name), params, type, body);
                                                                            System.out.println(RESULT);
                                                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DefDecl",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // DefDecl ::= DEF ID LPAR RPAR OptType Body 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DefDeclNode(new IdNode(name), type, body);
                                                          System.out.println(RESULT);
                                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DefDecl",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ParDecls ::= ParDecl SEMI ParDecls 
            {
              ArrayList<ParDeclNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<ParDeclNode> list = (ArrayList<ParDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((ParDeclNode) attrib);
                                                  RESULT = list;
                                                  System.out.println("ParDecls fittizio: " + RESULT);
                                               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ParDecls",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ParDecls ::= ParDecl 
            {
              ArrayList<ParDeclNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<ParDeclNode> list = new ArrayList<>();
                             list.add((ParDeclNode) attrib);
                             RESULT = list;
                             System.out.println("ParDecls fittizio: " + RESULT);
                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ParDecls",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ParDecl ::= PVars COLON Type 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<PVarNode> vars = (ArrayList<PVarNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ParDeclNode(vars, type);
                                          System.out.println(RESULT);
                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ParDecl",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // PVars ::= PVar COMMA PVars 
            {
              ArrayList<PVarNode> RESULT =null;
		int pvarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int pvarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object pvar = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<PVarNode> list = (ArrayList<PVarNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((PVarNode) pvar);
                                        RESULT = list;
                                        //System.out.println("PVars fittizio: " + RESULT);
                                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVars",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // PVars ::= PVar 
            {
              ArrayList<PVarNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<PVarNode> list = new ArrayList<>();
                       list.add((PVarNode) attrib);
                       RESULT = list;
                       //System.out.println("PVar fittizio: " + RESULT);
                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVars",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // PVar ::= ID 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new PVarNode(new IdNode(attrib)); System.out.println(RESULT);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVar",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // PVar ::= REF ID 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new PVarNode(new IdNode(attrib), true); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVar",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // OptType ::= COLON Type 
            {
              Object RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = type; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OptType",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // OptType ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OptType",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Body ::= LBRAC VarDecls Statements RBRAC 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<VarDeclNode> vars = (ArrayList<VarDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int statsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int statsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<StatOpNode> stats = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new BodyNode(vars, stats);
                                                       System.out.println(RESULT);
                                                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Body",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Statements ::= Stat Statements 
            {
              ArrayList<StatOpNode> RESULT =null;
		int statleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int statright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object stat = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<StatOpNode> list = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(0, (StatOpNode) stat);
                                            RESULT = list;
                                            //System.out.println("Statements Fittizio: " + RESULT);
                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Statements",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Statements ::= 
            {
              ArrayList<StatOpNode> RESULT =null;
		 ArrayList<StatOpNode> list = new ArrayList<>();
                             RESULT = list;
                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Statements",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Stat ::= Vars IN SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<IdNode> attrib = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new ReadOpNode(attrib); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Stat ::= Exprs OUT SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<ExprOpNode> attrib = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new WriteOpNode(attrib); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Stat ::= Exprs OUTNL SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<ExprOpNode> attrib = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new WriteOpNode(attrib, true); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Stat ::= Vars ASSIGN Exprs SEMI 
            {
              Object RESULT =null;
		int idsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<IdNode> ids = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int exprsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exprsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<ExprOpNode> exprs = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new AssignOpNode(ids, exprs); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Stat ::= FunCall SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = attrib; System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Stat ::= IF LPAR Expr RPAR THEN Body ELSE Body 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int body1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int body1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object body1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int body2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int body2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IfThenElseNode(expr, body1, body2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Stat ::= IF LPAR Expr RPAR THEN Body 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IfThenNode(expr, body); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Stat ::= WHILE LPAR Expr RPAR DO Body 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new WhileNode(expr, body); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Stat ::= RETURN Expr SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ReturnOpNode(attrib); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Vars ::= ID PIPE Vars 
            {
              ArrayList<IdNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<IdNode> list = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(new IdNode(attrib));
                                     RESULT = list;
                                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Vars",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // Vars ::= ID 
            {
              ArrayList<IdNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<IdNode> list = new ArrayList<>();
                    list.add(new IdNode(attrib));
                    RESULT = list;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Vars",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Exprs ::= Expr COMMA Exprs 
            {
              ArrayList<ExprOpNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<ExprOpNode> list = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((ExprOpNode) attrib);
                                          RESULT = list;
                                          System.out.println("Exprs Fittizio: " + RESULT);
                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exprs",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Exprs ::= Expr 
            {
              ArrayList<ExprOpNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<ExprOpNode> list = new ArrayList<>();
                       list.add((ExprOpNode) attrib);
                       RESULT = list;
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exprs",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // FunCall ::= ID LPAR Exprs RPAR 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int refleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int refright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<ExprOpNode> ref = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new FunCallNode(new IdNode (attrib), ref);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FunCall",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // FunCall ::= ID LPAR RPAR 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new FunCallNode(new IdNode (attrib)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FunCall",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // Expr ::= Expr ArithOp Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(attrib.equals("PLUS")) {RESULT = new AddNode(e1, e2); }
                                           else if(attrib.equals("MINUS")){ RESULT = new DiffNode(e1, e2); }
                                           else if(attrib.equals("TIMES")){ RESULT = new MulNode(e1, e2); }
                                           else if(attrib.equals("DIV")){ RESULT = new DivNode(e1, e2); }
                                           System.out.println(RESULT);
                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // Expr ::= Expr BoolOp Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(attrib.equals("AND")) {RESULT = new AndNode(e1, e2); }
                                                 else if(attrib.equals("OR")) { RESULT = new OrNode(e1, e2); }
                                                 System.out.println(RESULT);
                                              
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // Expr ::= Expr RelOp Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(attrib.equals("GT")) { RESULT = new GTNode(e1, e2); }
                                                else if(attrib.equals("GE")) { RESULT = new GENode(e1, e2); }
                                                else if(attrib.equals("LT")) { RESULT = new LTNode(e1, e2); }
                                                else if(attrib.equals("LE")) { RESULT = new LENode(e1, e2); }
                                                else if(attrib.equals("EQ")) { RESULT = new EQNode(e1, e2); }
                                                else if(attrib.equals("NE")) { RESULT = new NENode(e1, e2); }
                                                System.out.println(RESULT);
                                             
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // Expr ::= LPAR Expr RPAR 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e1; System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // Expr ::= MINUS Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new UMinusNode(e1); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // Expr ::= NOT Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new NotNode(e1); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // Expr ::= ID 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IdNode(attrib); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // Expr ::= FunCall 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib; System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // Expr ::= Constant 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib; System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // ArithOp ::= PLUS 
            {
              Object RESULT =null;
		 RESULT = "PLUS"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArithOp",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // ArithOp ::= MINUS 
            {
              Object RESULT =null;
		 RESULT = "MINUS"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArithOp",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // ArithOp ::= TIMES 
            {
              Object RESULT =null;
		 RESULT = "TIMES"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArithOp",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // ArithOp ::= DIV 
            {
              Object RESULT =null;
		 RESULT = "DIV"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArithOp",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // BoolOp ::= AND 
            {
              Object RESULT =null;
		 RESULT = "AND"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("BoolOp",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // BoolOp ::= OR 
            {
              Object RESULT =null;
		 RESULT = "OR"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("BoolOp",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // RelOp ::= GT 
            {
              Object RESULT =null;
		 RESULT = "GT"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("RelOp",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // RelOp ::= GE 
            {
              Object RESULT =null;
		 RESULT = "GE"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("RelOp",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // RelOp ::= LT 
            {
              Object RESULT =null;
		 RESULT = "LT"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("RelOp",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // RelOp ::= LE 
            {
              Object RESULT =null;
		 RESULT = "LE"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("RelOp",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // RelOp ::= EQ 
            {
              Object RESULT =null;
		 RESULT = "EQ"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("RelOp",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // RelOp ::= NE 
            {
              Object RESULT =null;
		 RESULT = "NE"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("RelOp",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
