
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione4;

import java_cup.runtime.*;
import java.util.ArrayList;
import esercitazione4.ast.IdNode;
import esercitazione4.ast.ExprOpNode;
import esercitazione4.ast.Constants.*;
import esercitazione4.ast.ArithOp.*;
import esercitazione4.ast.BoolOp.*;
import esercitazione4.ast.RelOp.*;
import esercitazione4.ast.FunCallNode;
import esercitazione4.ast.ProgramNode;
import esercitazione4.ast.DeclOpNode;
import esercitazione4.ast.DefDeclOp.DefDeclNode;
import esercitazione4.ast.ParDeclOp.*;
import esercitazione4.ast.BodyNode;
import esercitazione4.ast.StatOp.*;
import esercitazione4.ast.Type;
import esercitazione4.ast.VarDeclOp.*;
import esercitazione4.ast.SwitchStatNode;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\112\000\002\002\010\000\002\002\004\000\002\023" +
    "\004\000\002\023\004\000\002\023\002\000\002\025\004" +
    "\000\002\025\002\000\002\022\006\000\002\032\005\000" +
    "\002\032\007\000\002\032\003\000\002\032\005\000\002" +
    "\015\003\000\002\015\003\000\002\017\003\000\002\017" +
    "\003\000\002\017\003\000\002\017\003\000\002\017\003" +
    "\000\002\016\003\000\002\016\003\000\002\016\003\000" +
    "\002\016\003\000\002\016\003\000\002\016\003\000\002" +
    "\021\011\000\002\021\010\000\002\024\005\000\002\024" +
    "\003\000\002\020\005\000\002\031\005\000\002\031\003" +
    "\000\002\030\003\000\002\030\004\000\002\014\004\000" +
    "\002\014\002\000\002\010\006\000\002\011\004\000\002" +
    "\011\002\000\002\007\005\000\002\007\005\000\002\007" +
    "\005\000\002\007\006\000\002\007\004\000\002\007\012" +
    "\000\002\007\010\000\002\007\010\000\002\007\012\000" +
    "\002\007\005\000\002\027\021\000\002\026\005\000\002" +
    "\026\003\000\002\012\005\000\002\012\003\000\002\013" +
    "\006\000\002\013\005\000\002\006\005\000\002\006\005" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\005\000\002\006" +
    "\005\000\002\006\005\000\002\006\004\000\002\006\004" +
    "\000\002\006\003\000\002\006\003\000\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\251\000\004\023\005\001\002\000\004\002\253\001" +
    "\002\000\010\015\011\024\ufffd\064\006\001\002\000\010" +
    "\056\252\062\ufff7\063\117\001\002\000\004\062\245\001" +
    "\002\000\010\015\011\024\ufffd\064\006\001\002\000\004" +
    "\064\210\001\002\000\004\024\015\001\002\000\010\015" +
    "\011\024\ufffd\064\006\001\002\000\004\024\ufffe\001\002" +
    "\000\040\004\ufffb\007\ufffb\011\ufffb\012\ufffb\025\ufffb\026" +
    "\ufffb\027\ufffb\030\ufffb\031\ufffb\032\ufffb\033\ufffb\035\ufffb" +
    "\043\ufffb\052\ufffb\064\ufffb\001\002\000\040\004\032\007" +
    "\023\011\026\012\027\025\uffdb\026\031\027\037\030\035" +
    "\031\021\032\044\033\017\035\040\043\025\052\043\064" +
    "\034\001\002\000\050\034\uffe9\035\uffe9\036\uffe9\037\uffe9" +
    "\041\uffe9\042\uffe9\044\uffe9\045\uffe9\046\uffe9\047\uffe9\050" +
    "\uffe9\051\uffe9\053\uffe9\056\uffe9\057\uffe9\060\uffe9\062\uffe9" +
    "\066\uffe9\067\uffe9\001\002\000\044\004\032\007\023\011" +
    "\026\012\027\013\uffdb\025\uffdb\026\031\027\037\030\035" +
    "\031\021\032\044\033\017\035\040\043\025\052\043\055" +
    "\uffdb\064\154\001\002\000\050\034\uffeb\035\uffeb\036\uffeb" +
    "\037\uffeb\041\uffeb\042\uffeb\044\uffeb\045\uffeb\046\uffeb\047" +
    "\uffeb\050\uffeb\051\uffeb\053\uffeb\056\uffeb\057\uffeb\060\uffeb" +
    "\062\uffeb\066\uffeb\067\uffeb\001\002\000\050\034\uffb8\035" +
    "\uffb8\036\uffb8\037\uffb8\041\uffb8\042\uffb8\044\uffb8\045\uffb8" +
    "\046\uffb8\047\uffb8\050\uffb8\051\uffb8\053\uffb8\056\uffb8\057" +
    "\uffb8\060\uffb8\062\uffb8\066\uffb8\067\uffb8\001\002\000\004" +
    "\052\202\001\002\000\004\025\201\001\002\000\026\026" +
    "\031\027\037\030\035\031\021\032\044\033\017\035\040" +
    "\043\025\052\043\064\047\001\002\000\026\026\031\027" +
    "\037\030\035\031\021\032\044\033\017\035\040\043\025" +
    "\052\043\064\047\001\002\000\004\052\145\001\002\000" +
    "\042\034\uffb9\035\uffb9\036\uffb9\037\uffb9\041\uffb9\042\uffb9" +
    "\044\uffb9\045\uffb9\046\uffb9\047\uffb9\050\uffb9\051\uffb9\057" +
    "\uffb9\060\144\066\uffb9\067\uffb9\001\002\000\050\034\uffee" +
    "\035\uffee\036\uffee\037\uffee\041\uffee\042\uffee\044\uffee\045" +
    "\uffee\046\uffee\047\uffee\050\uffee\051\uffee\053\uffee\056\uffee" +
    "\057\uffee\060\uffee\062\uffee\066\uffee\067\uffee\001\002\000" +
    "\004\052\131\001\002\000\044\034\060\035\054\036\064" +
    "\037\062\041\055\042\070\044\063\045\056\046\067\047" +
    "\061\050\057\051\066\053\uffcc\057\127\060\uffcc\066\uffcc" +
    "\067\uffcc\001\002\000\054\034\uffba\035\uffba\036\uffba\037" +
    "\uffba\041\uffba\042\uffba\044\uffba\045\uffba\046\uffba\047\uffba" +
    "\050\uffba\051\uffba\052\050\056\120\057\uffba\061\uffce\062" +
    "\ufff7\063\117\065\uffce\066\uffba\067\uffba\001\002\000\050" +
    "\034\uffec\035\uffec\036\uffec\037\uffec\041\uffec\042\uffec\044" +
    "\uffec\045\uffec\046\uffec\047\uffec\050\uffec\051\uffec\053\uffec" +
    "\056\uffec\057\uffec\060\uffec\062\uffec\066\uffec\067\uffec\001" +
    "\002\000\042\004\ufffc\007\ufffc\011\ufffc\012\ufffc\025\ufffc" +
    "\026\ufffc\027\ufffc\030\ufffc\031\ufffc\032\ufffc\033\ufffc\035" +
    "\ufffc\043\ufffc\052\ufffc\055\ufffc\064\ufffc\001\002\000\050" +
    "\034\uffed\035\uffed\036\uffed\037\uffed\041\uffed\042\uffed\044" +
    "\uffed\045\uffed\046\uffed\047\uffed\050\uffed\051\uffed\053\uffed" +
    "\056\uffed\057\uffed\060\uffed\062\uffed\066\uffed\067\uffed\001" +
    "\002\000\026\026\031\027\037\030\035\031\021\032\044" +
    "\033\017\035\040\043\025\052\043\064\047\001\002\000" +
    "\006\066\112\067\113\001\002\000\006\061\106\065\105" +
    "\001\002\000\026\026\031\027\037\030\035\031\021\032" +
    "\044\033\017\035\040\043\025\052\043\064\047\001\002" +
    "\000\050\034\uffea\035\uffea\036\uffea\037\uffea\041\uffea\042" +
    "\uffea\044\uffea\045\uffea\046\uffea\047\uffea\050\uffea\051\uffea" +
    "\053\uffea\056\uffea\057\uffea\060\uffea\062\uffea\066\uffea\067" +
    "\uffea\001\002\000\034\034\060\035\054\036\064\037\062" +
    "\041\055\042\070\044\063\045\056\046\067\047\061\050" +
    "\057\051\066\053\065\001\002\000\050\034\uffb9\035\uffb9" +
    "\036\uffb9\037\uffb9\041\uffb9\042\uffb9\044\uffb9\045\uffb9\046" +
    "\uffb9\047\uffb9\050\uffb9\051\uffb9\053\uffb9\056\uffb9\057\uffb9" +
    "\060\uffb9\062\uffb9\066\uffb9\067\uffb9\001\002\000\052\034" +
    "\uffba\035\uffba\036\uffba\037\uffba\041\uffba\042\uffba\044\uffba" +
    "\045\uffba\046\uffba\047\uffba\050\uffba\051\uffba\052\050\053" +
    "\uffba\056\uffba\057\uffba\060\uffba\062\uffba\066\uffba\067\uffba" +
    "\001\002\000\030\026\031\027\037\030\035\031\021\032" +
    "\044\033\017\035\040\043\025\052\043\053\052\064\047" +
    "\001\002\000\004\053\053\001\002\000\050\034\uffca\035" +
    "\uffca\036\uffca\037\uffca\041\uffca\042\uffca\044\uffca\045\uffca" +
    "\046\uffca\047\uffca\050\uffca\051\uffca\053\uffca\056\uffca\057" +
    "\uffca\060\uffca\062\uffca\066\uffca\067\uffca\001\002\000\050" +
    "\034\uffcb\035\uffcb\036\uffcb\037\uffcb\041\uffcb\042\uffcb\044" +
    "\uffcb\045\uffcb\046\uffcb\047\uffcb\050\uffcb\051\uffcb\053\uffcb" +
    "\056\uffcb\057\uffcb\060\uffcb\062\uffcb\066\uffcb\067\uffcb\001" +
    "\002\000\026\026\031\027\037\030\035\031\021\032\044" +
    "\033\017\035\040\043\025\052\043\064\047\001\002\000" +
    "\026\026\031\027\037\030\035\031\021\032\044\033\017" +
    "\035\040\043\025\052\043\064\047\001\002\000\026\026" +
    "\031\027\037\030\035\031\021\032\044\033\017\035\040" +
    "\043\025\052\043\064\047\001\002\000\026\026\031\027" +
    "\037\030\035\031\021\032\044\033\017\035\040\043\025" +
    "\052\043\064\047\001\002\000\026\026\031\027\037\030" +
    "\035\031\021\032\044\033\017\035\040\043\025\052\043" +
    "\064\047\001\002\000\026\026\031\027\037\030\035\031" +
    "\021\032\044\033\017\035\040\043\025\052\043\064\047" +
    "\001\002\000\026\026\031\027\037\030\035\031\021\032" +
    "\044\033\017\035\040\043\025\052\043\064\047\001\002" +
    "\000\026\026\031\027\037\030\035\031\021\032\044\033" +
    "\017\035\040\043\025\052\043\064\047\001\002\000\026" +
    "\026\031\027\037\030\035\031\021\032\044\033\017\035" +
    "\040\043\025\052\043\064\047\001\002\000\050\034\uffbd" +
    "\035\uffbd\036\uffbd\037\uffbd\041\uffbd\042\uffbd\044\uffbd\045" +
    "\uffbd\046\uffbd\047\uffbd\050\uffbd\051\uffbd\053\uffbd\056\uffbd" +
    "\057\uffbd\060\uffbd\062\uffbd\066\uffbd\067\uffbd\001\002\000" +
    "\026\026\031\027\037\030\035\031\021\032\044\033\017" +
    "\035\040\043\025\052\043\064\047\001\002\000\026\026" +
    "\031\027\037\030\035\031\021\032\044\033\017\035\040" +
    "\043\025\052\043\064\047\001\002\000\026\026\031\027" +
    "\037\030\035\031\021\032\044\033\017\035\040\043\025" +
    "\052\043\064\047\001\002\000\050\034\060\035\054\036" +
    "\064\037\062\041\055\042\uffc4\044\063\045\056\046\067" +
    "\047\061\050\057\051\066\053\uffc4\056\uffc4\057\uffc4\060" +
    "\uffc4\062\uffc4\066\uffc4\067\uffc4\001\002\000\050\034\060" +
    "\035\054\036\064\037\062\041\uffc1\042\uffc1\044\uffc1\045" +
    "\uffc1\046\uffc1\047\uffc1\050\uffc1\051\uffc1\053\uffc1\056\uffc1" +
    "\057\uffc1\060\uffc1\062\uffc1\066\uffc1\067\uffc1\001\002\000" +
    "\050\034\060\035\054\036\064\037\062\041\uffbe\042\uffbe" +
    "\044\uffbe\045\uffbe\046\uffbe\047\uffbe\050\uffbe\051\uffbe\053" +
    "\uffbe\056\uffbe\057\uffbe\060\uffbe\062\uffbe\066\uffbe\067\uffbe" +
    "\001\002\000\050\034\uffc7\035\uffc7\036\uffc7\037\uffc7\041" +
    "\uffc7\042\uffc7\044\uffc7\045\uffc7\046\uffc7\047\uffc7\050\uffc7" +
    "\051\uffc7\053\uffc7\056\uffc7\057\uffc7\060\uffc7\062\uffc7\066" +
    "\uffc7\067\uffc7\001\002\000\050\034\060\035\054\036\064" +
    "\037\062\041\uffc3\042\uffc3\044\uffc3\045\uffc3\046\uffc3\047" +
    "\uffc3\050\uffc3\051\uffc3\053\uffc3\056\uffc3\057\uffc3\060\uffc3" +
    "\062\uffc3\066\uffc3\067\uffc3\001\002\000\050\034\uffc6\035" +
    "\uffc6\036\uffc6\037\uffc6\041\uffc6\042\uffc6\044\uffc6\045\uffc6" +
    "\046\uffc6\047\uffc6\050\uffc6\051\uffc6\053\uffc6\056\uffc6\057" +
    "\uffc6\060\uffc6\062\uffc6\066\uffc6\067\uffc6\001\002\000\050" +
    "\034\060\035\054\036\064\037\062\041\uffc0\042\uffc0\044" +
    "\uffc0\045\uffc0\046\uffc0\047\uffc0\050\uffc0\051\uffc0\053\uffc0" +
    "\056\uffc0\057\uffc0\060\uffc0\062\uffc0\066\uffc0\067\uffc0\001" +
    "\002\000\050\034\uffc9\035\uffc9\036\064\037\062\041\uffc9" +
    "\042\uffc9\044\uffc9\045\uffc9\046\uffc9\047\uffc9\050\uffc9\051" +
    "\uffc9\053\uffc9\056\uffc9\057\uffc9\060\uffc9\062\uffc9\066\uffc9" +
    "\067\uffc9\001\002\000\050\034\060\035\054\036\064\037" +
    "\062\041\uffbf\042\uffbf\044\uffbf\045\uffbf\046\uffbf\047\uffbf" +
    "\050\uffbf\051\uffbf\053\uffbf\056\uffbf\057\uffbf\060\uffbf\062" +
    "\uffbf\066\uffbf\067\uffbf\001\002\000\050\034\060\035\054" +
    "\036\064\037\062\041\uffc2\042\uffc2\044\uffc2\045\uffc2\046" +
    "\uffc2\047\uffc2\050\uffc2\051\uffc2\053\uffc2\056\uffc2\057\uffc2" +
    "\060\uffc2\062\uffc2\066\uffc2\067\uffc2\001\002\000\050\034" +
    "\060\035\054\036\064\037\062\041\uffc5\042\uffc5\044\063" +
    "\045\056\046\067\047\061\050\057\051\066\053\uffc5\056" +
    "\uffc5\057\uffc5\060\uffc5\062\uffc5\066\uffc5\067\uffc5\001\002" +
    "\000\050\034\uffc8\035\uffc8\036\064\037\062\041\uffc8\042" +
    "\uffc8\044\uffc8\045\uffc8\046\uffc8\047\uffc8\050\uffc8\051\uffc8" +
    "\053\uffc8\056\uffc8\057\uffc8\060\uffc8\062\uffc8\066\uffc8\067" +
    "\uffc8\001\002\000\004\060\111\001\002\000\026\026\031" +
    "\027\037\030\035\031\021\032\044\033\017\035\040\043" +
    "\025\052\043\064\047\001\002\000\004\060\110\001\002" +
    "\000\044\004\uffd7\007\uffd7\011\uffd7\012\uffd7\013\uffd7\025" +
    "\uffd7\026\uffd7\027\uffd7\030\uffd7\031\uffd7\032\uffd7\033\uffd7" +
    "\035\uffd7\043\uffd7\052\uffd7\055\uffd7\064\uffd7\001\002\000" +
    "\044\004\uffda\007\uffda\011\uffda\012\uffda\013\uffda\025\uffda" +
    "\026\uffda\027\uffda\030\uffda\031\uffda\032\uffda\033\uffda\035" +
    "\uffda\043\uffda\052\uffda\055\uffda\064\uffda\001\002\000\004" +
    "\060\115\001\002\000\004\060\114\001\002\000\044\004" +
    "\uffd8\007\uffd8\011\uffd8\012\uffd8\013\uffd8\025\uffd8\026\uffd8" +
    "\027\uffd8\030\uffd8\031\uffd8\032\uffd8\033\uffd8\035\uffd8\043" +
    "\uffd8\052\uffd8\055\uffd8\064\uffd8\001\002\000\044\004\uffd9" +
    "\007\uffd9\011\uffd9\012\uffd9\013\uffd9\025\uffd9\026\uffd9\027" +
    "\uffd9\030\uffd9\031\uffd9\032\uffd9\033\uffd9\035\uffd9\043\uffd9" +
    "\052\uffd9\055\uffd9\064\uffd9\001\002\000\050\034\uffbc\035" +
    "\uffbc\036\uffbc\037\uffbc\041\uffbc\042\uffbc\044\uffbc\045\uffbc" +
    "\046\uffbc\047\uffbc\050\uffbc\051\uffbc\053\uffbc\056\uffbc\057" +
    "\uffbc\060\uffbc\062\uffbc\066\uffbc\067\uffbc\001\002\000\026" +
    "\026\031\027\037\030\035\031\021\032\044\033\017\035" +
    "\040\043\025\052\043\064\047\001\002\000\004\064\121" +
    "\001\002\000\014\056\120\061\uffce\062\ufff7\063\117\065" +
    "\uffce\001\002\000\004\062\ufff9\001\002\000\006\061\uffcf" +
    "\065\uffcf\001\002\000\036\034\060\035\054\036\064\037" +
    "\062\041\055\042\070\044\063\045\056\046\067\047\061" +
    "\050\057\051\066\056\125\062\ufff6\001\002\000\004\064" +
    "\006\001\002\000\004\062\ufff8\001\002\000\026\026\031" +
    "\027\037\030\035\031\021\032\044\033\017\035\040\043" +
    "\025\052\043\064\047\001\002\000\012\053\uffcd\060\uffcd" +
    "\066\uffcd\067\uffcd\001\002\000\026\026\031\027\037\030" +
    "\035\031\021\032\044\033\017\035\040\043\025\052\043" +
    "\064\047\001\002\000\034\034\060\035\054\036\064\037" +
    "\062\041\055\042\070\044\063\045\056\046\067\047\061" +
    "\050\057\051\066\053\133\001\002\000\004\005\134\001" +
    "\002\000\004\054\135\001\002\000\040\004\ufffb\007\ufffb" +
    "\011\ufffb\012\ufffb\026\ufffb\027\ufffb\030\ufffb\031\ufffb\032" +
    "\ufffb\033\ufffb\035\ufffb\043\ufffb\052\ufffb\055\ufffb\064\ufffb" +
    "\001\002\000\046\004\uffd4\006\137\007\uffd4\011\uffd4\012" +
    "\uffd4\013\uffd4\025\uffd4\026\uffd4\027\uffd4\030\uffd4\031\uffd4" +
    "\032\uffd4\033\uffd4\035\uffd4\043\uffd4\052\uffd4\055\uffd4\064" +
    "\uffd4\001\002\000\004\054\135\001\002\000\044\004\uffd5" +
    "\007\uffd5\011\uffd5\012\uffd5\013\uffd5\025\uffd5\026\uffd5\027" +
    "\uffd5\030\uffd5\031\uffd5\032\uffd5\033\uffd5\035\uffd5\043\uffd5" +
    "\052\uffd5\055\uffd5\064\uffd5\001\002\000\040\004\032\007" +
    "\023\011\026\012\027\026\031\027\037\030\035\031\021" +
    "\032\044\033\017\035\040\043\025\052\043\055\uffdb\064" +
    "\034\001\002\000\004\055\143\001\002\000\052\004\uffdd" +
    "\006\uffdd\007\uffdd\011\uffdd\012\uffdd\013\uffdd\015\uffdd\024" +
    "\uffdd\025\uffdd\026\uffdd\027\uffdd\030\uffdd\031\uffdd\032\uffdd" +
    "\033\uffdd\035\uffdd\043\uffdd\052\uffdd\055\uffdd\064\uffdd\001" +
    "\002\000\044\004\uffd6\007\uffd6\011\uffd6\012\uffd6\013\uffd6" +
    "\025\uffd6\026\uffd6\027\uffd6\030\uffd6\031\uffd6\032\uffd6\033" +
    "\uffd6\035\uffd6\043\uffd6\052\uffd6\055\uffd6\064\uffd6\001\002" +
    "\000\004\064\146\001\002\000\004\053\147\001\002\000" +
    "\016\026\031\027\037\030\035\031\021\032\044\033\017" +
    "\001\002\000\004\025\173\001\002\000\004\062\152\001" +
    "\002\000\040\004\032\007\023\011\026\012\027\013\uffdb" +
    "\026\031\027\037\030\035\031\021\032\044\033\017\035" +
    "\040\043\025\052\043\064\154\001\002\000\004\013\157" +
    "\001\002\000\050\034\uffba\035\uffba\036\uffba\037\uffba\041" +
    "\uffba\042\uffba\044\uffba\045\uffba\046\uffba\047\uffba\050\uffba" +
    "\051\uffba\052\050\056\155\057\uffba\061\uffce\065\uffce\066" +
    "\uffba\067\uffba\001\002\000\004\064\156\001\002\000\010" +
    "\056\155\061\uffce\065\uffce\001\002\000\004\060\160\001" +
    "\002\000\016\026\031\027\037\030\035\031\021\032\044" +
    "\033\017\001\002\000\004\062\162\001\002\000\040\004" +
    "\032\007\023\011\026\012\027\013\uffdb\026\031\027\037" +
    "\030\035\031\021\032\044\033\017\035\040\043\025\052" +
    "\043\064\154\001\002\000\004\013\164\001\002\000\004" +
    "\060\165\001\002\000\016\026\031\027\037\030\035\031" +
    "\021\032\044\033\017\001\002\000\004\062\167\001\002" +
    "\000\040\004\032\007\023\011\026\012\027\013\uffdb\026" +
    "\031\027\037\030\035\031\021\032\044\033\017\035\040" +
    "\043\025\052\043\064\154\001\002\000\004\013\171\001" +
    "\002\000\004\060\172\001\002\000\004\025\uffd0\001\002" +
    "\000\004\012\174\001\002\000\004\060\175\001\002\000" +
    "\044\004\uffd2\007\uffd2\011\uffd2\012\uffd2\013\uffd2\025\uffd2" +
    "\026\uffd2\027\uffd2\030\uffd2\031\uffd2\032\uffd2\033\uffd2\035" +
    "\uffd2\043\uffd2\052\uffd2\055\uffd2\064\uffd2\001\002\000\034" +
    "\034\060\035\054\036\064\037\062\041\055\042\070\044" +
    "\063\045\056\046\067\047\061\050\057\051\066\060\177" +
    "\001\002\000\044\004\uffd1\007\uffd1\011\uffd1\012\uffd1\013" +
    "\uffd1\025\uffd1\026\uffd1\027\uffd1\030\uffd1\031\uffd1\032\uffd1" +
    "\033\uffd1\035\uffd1\043\uffd1\052\uffd1\055\uffd1\064\uffd1\001" +
    "\002\000\050\034\060\035\054\036\064\037\062\041\uffbb" +
    "\042\uffbb\044\063\045\056\046\067\047\061\050\057\051" +
    "\066\053\uffbb\056\uffbb\057\uffbb\060\uffbb\062\uffbb\066\uffbb" +
    "\067\uffbb\001\002\000\004\002\001\001\002\000\026\026" +
    "\031\027\037\030\035\031\021\032\044\033\017\035\040" +
    "\043\025\052\043\064\047\001\002\000\034\034\060\035" +
    "\054\036\064\037\062\041\055\042\070\044\063\045\056" +
    "\046\067\047\061\050\057\051\066\053\204\001\002\000" +
    "\004\010\205\001\002\000\004\054\135\001\002\000\044" +
    "\004\uffd3\007\uffd3\011\uffd3\012\uffd3\013\uffd3\025\uffd3\026" +
    "\uffd3\027\uffd3\030\uffd3\031\uffd3\032\uffd3\033\uffd3\035\uffd3" +
    "\043\uffd3\052\uffd3\055\uffd3\064\uffd3\001\002\000\010\013" +
    "\uffdc\025\uffdc\055\uffdc\001\002\000\004\052\211\001\002" +
    "\000\010\014\215\053\217\064\212\001\002\000\006\057" +
    "\uffe1\062\uffe1\001\002\000\004\062\242\001\002\000\006" +
    "\057\240\062\uffe2\001\002\000\004\064\237\001\002\000" +
    "\004\053\234\001\002\000\006\054\uffde\062\223\001\002" +
    "\000\006\053\uffe5\060\221\001\002\000\006\014\215\064" +
    "\212\001\002\000\004\053\uffe6\001\002\000\014\016\233" +
    "\017\231\020\230\021\226\022\232\001\002\000\004\054" +
    "\135\001\002\000\010\015\uffe7\024\uffe7\064\uffe7\001\002" +
    "\000\010\053\ufff0\054\ufff0\060\ufff0\001\002\000\004\054" +
    "\uffdf\001\002\000\010\053\ufff1\054\ufff1\060\ufff1\001\002" +
    "\000\010\053\ufff2\054\ufff2\060\ufff2\001\002\000\010\053" +
    "\uffef\054\uffef\060\uffef\001\002\000\010\053\ufff3\054\ufff3" +
    "\060\ufff3\001\002\000\006\054\uffde\062\223\001\002\000" +
    "\004\054\135\001\002\000\010\015\uffe8\024\uffe8\064\uffe8" +
    "\001\002\000\006\057\uffe0\062\uffe0\001\002\000\006\014" +
    "\215\064\212\001\002\000\004\062\uffe3\001\002\000\014" +
    "\016\233\017\231\020\230\021\226\022\232\001\002\000" +
    "\006\053\uffe4\060\uffe4\001\002\000\004\024\uffff\001\002" +
    "\000\030\016\233\017\231\020\230\021\226\022\232\026" +
    "\031\027\037\030\035\031\021\032\044\033\017\001\002" +
    "\000\004\060\ufff5\001\002\000\004\060\251\001\002\000" +
    "\004\060\ufff4\001\002\000\046\004\ufffa\007\ufffa\011\ufffa" +
    "\012\ufffa\015\ufffa\024\ufffa\025\ufffa\026\ufffa\027\ufffa\030" +
    "\ufffa\031\ufffa\032\ufffa\033\ufffa\035\ufffa\043\ufffa\052\ufffa" +
    "\055\ufffa\064\ufffa\001\002\000\004\064\006\001\002\000" +
    "\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\251\000\004\002\003\001\001\000\002\001\001\000" +
    "\012\021\012\022\007\023\011\032\006\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\021\012\022\007\023" +
    "\243\032\006\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\021\012\022\007\023\013\032\006\001\001\000" +
    "\002\001\001\000\004\025\015\001\001\000\024\006\032" +
    "\007\017\011\023\012\040\013\027\016\021\022\035\026" +
    "\041\032\006\001\001\000\002\001\001\000\020\006\032" +
    "\007\017\011\206\012\040\013\027\016\021\026\041\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\006\177\013\045\016\021\001" +
    "\001\000\010\006\175\013\045\016\021\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\006\115\013" +
    "\045\016\021\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\006\044\013\045\016\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\006\032\012\050\013\045\016\021\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\006\103\013\045\016\021\001\001\000\010\006\102\013" +
    "\045\016\021\001\001\000\010\006\101\013\045\016\021" +
    "\001\001\000\010\006\100\013\045\016\021\001\001\000" +
    "\010\006\077\013\045\016\021\001\001\000\010\006\076" +
    "\013\045\016\021\001\001\000\010\006\075\013\045\016" +
    "\021\001\001\000\010\006\074\013\045\016\021\001\001" +
    "\000\010\006\073\013\045\016\021\001\001\000\002\001" +
    "\001\000\010\006\072\013\045\016\021\001\001\000\010" +
    "\006\071\013\045\016\021\001\001\000\010\006\070\013" +
    "\045\016\021\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\006\032\012\106\013\045" +
    "\016\021\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\006" +
    "\123\013\045\016\021\001\001\000\006\026\122\032\121" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\032\125\001\001\000\002" +
    "\001\001\000\012\006\032\012\127\013\045\016\021\001" +
    "\001\000\002\001\001\000\010\006\131\013\045\016\021" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\010" +
    "\135\001\001\000\004\025\140\001\001\000\002\001\001" +
    "\000\004\010\137\001\001\000\002\001\001\000\024\006" +
    "\032\007\017\011\141\012\040\013\027\016\021\022\035" +
    "\026\041\032\006\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\016\150\027\147\001\001\000\002\001\001\000" +
    "\002\001\001\000\020\006\032\007\017\011\152\012\040" +
    "\013\027\016\021\026\041\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\026\122\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\016\160\001\001\000\002\001" +
    "\001\000\020\006\032\007\017\011\162\012\040\013\027" +
    "\016\021\026\041\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\016\165\001\001\000\002\001\001\000\020" +
    "\006\032\007\017\011\167\012\040\013\027\016\021\026" +
    "\041\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\006\202\013\045\016\021\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\010\205" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\020\217\024\215\030\213\031\212\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\014\223\001\001" +
    "\000\002\001\001\000\012\020\217\024\221\030\213\031" +
    "\212\001\001\000\002\001\001\000\004\017\226\001\001" +
    "\000\004\010\224\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\234\001" +
    "\001\000\004\010\235\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\030\213\031\240\001\001\000\002\001" +
    "\001\000\004\017\242\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\015\246\016\247\017\245\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\032\121\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Programma ::= PROGRAM Decls BEGIN VarDecls Statements END 
            {
              Object RESULT =null;
		int declsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int declsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		ArrayList<DeclOpNode> decls = (ArrayList<DeclOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<VarDeclNode> vars = (ArrayList<VarDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int statsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int statsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<StatOpNode> stats = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ProgramNode(decls, vars, stats);
                                                                              //System.out.println(RESULT);
                                                                           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Programma",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Programma EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Decls ::= VarDecl Decls 
            {
              ArrayList<DeclOpNode> RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object var = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<DeclOpNode> list = (ArrayList<DeclOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(0, (VarDeclNode) var);
                                    RESULT = list;
                                    //System.out.println("VarDecls Fittizio: " + RESULT);
                                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Decls",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Decls ::= DefDecl Decls 
            {
              ArrayList<DeclOpNode> RESULT =null;
		int defleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int defright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object def = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<DeclOpNode> list = (ArrayList<DeclOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(0, (DefDeclNode) def);
                                  RESULT = list;
                                  //System.out.println("DefDecls Fittizio: " + RESULT);
                               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Decls",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Decls ::= 
            {
              ArrayList<DeclOpNode> RESULT =null;
		 ArrayList<DeclOpNode> list = new ArrayList<>();
                       RESULT = list;
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Decls",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // VarDecls ::= VarDecls VarDecl 
            {
              ArrayList<VarDeclNode> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<VarDeclNode> list = (ArrayList<VarDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object var = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((VarDeclNode) var);
                                          RESULT = list;
                                          //System.out.println("VarDecls Fittizio: " + RESULT);
                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarDecls",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // VarDecls ::= 
            {
              ArrayList<VarDeclNode> RESULT =null;
		 ArrayList<VarDeclNode> list = new ArrayList<>();
                         RESULT = list;
                      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarDecls",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // VarDecl ::= VarsOptInit COLON TypeOrConstant SEMI 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<VarOptInitNode> vars = (ArrayList<VarOptInitNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int typeOrConstantleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeOrConstantright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object typeOrConstant = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new VarDeclNode(vars, typeOrConstant);
                                                                        //System.out.println(RESULT);
                                                                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarDecl",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // VarsOptInit ::= ID PIPE VarsOptInit 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<VarOptInitNode> list = (ArrayList<VarOptInitNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(new VarOptInitNode(new IdNode(attrib)));
                                                   RESULT = list;
                                                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // VarsOptInit ::= ID ASSIGNDECL Expr PIPE VarsOptInit 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<VarOptInitNode> list = (ArrayList<VarOptInitNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(new VarOptInitNode(new IdNode(id), expr));
                                                                  RESULT = list;
                                                                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // VarsOptInit ::= ID 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<VarOptInitNode> list = new ArrayList<>();
                           list.add(new VarOptInitNode(new IdNode(attrib)));
                           RESULT = list;
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // VarsOptInit ::= ID ASSIGNDECL Expr 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<VarOptInitNode> list = new ArrayList<>();
                                            list.add(new VarOptInitNode(new IdNode(id), expr));
                                            RESULT = list;
                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // TypeOrConstant ::= Type 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib;  /*System.out.println("Type Fittizio: " + RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TypeOrConstant",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // TypeOrConstant ::= Constant 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib; /*System.out.println("Constant Fittizio: " + RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TypeOrConstant",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Type ::= INT 
            {
              Object RESULT =null;
		 RESULT = Type.INT; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Type ::= BOOL 
            {
              Object RESULT =null;
		 RESULT = Type.BOOL; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Type ::= DOUBLE 
            {
              Object RESULT =null;
		 RESULT = Type.DOUBLE; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Type ::= STRING 
            {
              Object RESULT =null;
		 RESULT = Type.STRING; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Type ::= CHAR 
            {
              Object RESULT =null;
		 RESULT = Type.CHAR; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Constant ::= TRUE 
            {
              Object RESULT =null;
		 RESULT = new BoolNode(true); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Constant ::= FALSE 
            {
              Object RESULT =null;
		 RESULT = new BoolNode(false); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Constant ::= INT_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IntNode((int) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Constant ::= DOUBLE_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DoubleNode((double) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Constant ::= CHAR_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CharNode((char) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Constant ::= STRING_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new StringNode((String) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // DefDecl ::= DEF ID LPAR ParDecls RPAR OptType Body 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<ParDeclNode> params = (ArrayList<ParDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DefDeclNode(new IdNode(name), params, type, body);
                                                                            //System.out.println(RESULT);
                                                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DefDecl",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // DefDecl ::= DEF ID LPAR RPAR OptType Body 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DefDeclNode(new IdNode(name), type, body);
                                                          //System.out.println(RESULT);
                                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DefDecl",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ParDecls ::= ParDecl SEMI ParDecls 
            {
              ArrayList<ParDeclNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<ParDeclNode> list = (ArrayList<ParDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((ParDeclNode) attrib);
                                                  RESULT = list;
                                                  //System.out.println("ParDecls fittizio: " + RESULT);
                                               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ParDecls",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ParDecls ::= ParDecl 
            {
              ArrayList<ParDeclNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<ParDeclNode> list = new ArrayList<>();
                             list.add((ParDeclNode) attrib);
                             RESULT = list;
                             //System.out.println("ParDecls fittizio: " + RESULT);
                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ParDecls",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ParDecl ::= PVars COLON Type 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<PVarNode> vars = (ArrayList<PVarNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ParDeclNode(vars, type);
                                          //System.out.println(RESULT);
                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ParDecl",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // PVars ::= PVar COMMA PVars 
            {
              ArrayList<PVarNode> RESULT =null;
		int pvarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int pvarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object pvar = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<PVarNode> list = (ArrayList<PVarNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((PVarNode) pvar);
                                        RESULT = list;
                                        //System.out.println("PVars fittizio: " + RESULT);
                                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVars",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // PVars ::= PVar 
            {
              ArrayList<PVarNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<PVarNode> list = new ArrayList<>();
                       list.add((PVarNode) attrib);
                       RESULT = list;
                       //System.out.println("PVar fittizio: " + RESULT);
                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVars",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // PVar ::= ID 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new PVarNode(new IdNode(attrib)); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVar",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // PVar ::= REF ID 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new PVarNode(new IdNode(attrib), true); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVar",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // OptType ::= COLON Type 
            {
              Object RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = type; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OptType",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // OptType ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OptType",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Body ::= LBRAC VarDecls Statements RBRAC 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<VarDeclNode> vars = (ArrayList<VarDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int statsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int statsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<StatOpNode> stats = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new BodyNode(vars, stats);
                                                       //System.out.println(RESULT);
                                                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Body",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Statements ::= Stat Statements 
            {
              ArrayList<StatOpNode> RESULT =null;
		int statleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int statright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object stat = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<StatOpNode> list = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(0, (StatOpNode) stat);
                                            RESULT = list;
                                            //System.out.println("Statements Fittizio: " + RESULT);
                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Statements",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Statements ::= 
            {
              ArrayList<StatOpNode> RESULT =null;
		 ArrayList<StatOpNode> list = new ArrayList<>();
                             RESULT = list;
                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Statements",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Stat ::= Vars IN SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<IdNode> attrib = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new ReadOpNode(attrib); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Stat ::= Exprs OUT SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<ExprOpNode> attrib = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new WriteOpNode(attrib); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Stat ::= Exprs OUTNL SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<ExprOpNode> attrib = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new WriteOpNode(attrib, true); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Stat ::= Vars ASSIGN Exprs SEMI 
            {
              Object RESULT =null;
		int idsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<IdNode> ids = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int exprsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exprsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<ExprOpNode> exprs = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new AssignOpNode(ids, exprs); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Stat ::= FunCall SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = attrib; /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Stat ::= IF LPAR Expr RPAR THEN Body ELSE Body 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int body1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int body1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object body1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int body2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int body2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IfThenElseNode(expr, body1, body2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Stat ::= IF LPAR Expr RPAR THEN Body 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IfThenNode(expr, body); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Stat ::= WHILE LPAR Expr RPAR DO Body 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new WhileNode(expr, body); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Stat ::= SWITCH LPAR ID RPAR SwitchStat END SWITCH SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int switchStatsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int switchStatsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<SwitchStatNode> switchStats = (ArrayList<SwitchStatNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		 RESULT = new SwitchNode(new IdNode(attrib), switchStats); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Stat ::= RETURN Expr SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ReturnOpNode(attrib); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // SwitchStat ::= Constant COLON Statements STOP SEMI Constant COLON Statements STOP SEMI Constant COLON Statements STOP SEMI 
            {
              ArrayList<SwitchStatNode> RESULT =null;
		int const1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-14)).left;
		int const1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-14)).right;
		Object const1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-14)).value;
		int stats1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)).left;
		int stats1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)).right;
		ArrayList<StatOpNode> stats1 = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-12)).value;
		int const2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).left;
		int const2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)).right;
		Object const2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;
		int stats2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int stats2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		ArrayList<StatOpNode> stats2 = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int const3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int const3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object const3 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int stats3left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int stats3right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<StatOpNode> stats3 = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 SwitchStatNode s1 = new SwitchStatNode(const1, stats1);
                SwitchStatNode s2 = new SwitchStatNode(const2, stats2);
                SwitchStatNode s3 = new SwitchStatNode(const3, stats3);
                ArrayList<SwitchStatNode> list = new ArrayList<>();
                list.add(s1);
                list.add(s2);
                list.add(s3);
                RESULT = list;
                System.out.println(RESULT);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("SwitchStat",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-14)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Vars ::= ID PIPE Vars 
            {
              ArrayList<IdNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<IdNode> list = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(new IdNode(attrib));
                                     RESULT = list;
                                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Vars",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Vars ::= ID 
            {
              ArrayList<IdNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<IdNode> list = new ArrayList<>();
                    list.add(new IdNode(attrib));
                    RESULT = list;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Vars",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // Exprs ::= Expr COMMA Exprs 
            {
              ArrayList<ExprOpNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<ExprOpNode> list = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((ExprOpNode) attrib);
                                          RESULT = list;
                                          //System.out.println("Exprs Fittizio: " + RESULT);
                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exprs",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // Exprs ::= Expr 
            {
              ArrayList<ExprOpNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<ExprOpNode> list = new ArrayList<>();
                       list.add((ExprOpNode) attrib);
                       RESULT = list;
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exprs",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // FunCall ::= ID LPAR Exprs RPAR 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int refleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int refright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<ExprOpNode> ref = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new FunCallNode(new IdNode (attrib), ref);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FunCall",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // FunCall ::= ID LPAR RPAR 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new FunCallNode(new IdNode (attrib)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FunCall",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // Expr ::= Expr PLUS Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AddNode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // Expr ::= Expr MINUS Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DiffNode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // Expr ::= Expr TIMES Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MulNode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // Expr ::= Expr DIV Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DivNode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // Expr ::= Expr AND Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AndNode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // Expr ::= Expr OR Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new OrNode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // Expr ::= Expr GT Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new GTNode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // Expr ::= Expr GE Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new GENode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // Expr ::= Expr LT Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LTNode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // Expr ::= Expr LE Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LENode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // Expr ::= Expr EQ Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new EQNode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // Expr ::= Expr NE Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NENode(e1, e2); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // Expr ::= LPAR Expr RPAR 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e1; /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // Expr ::= MINUS Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new UMinusNode(e1); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // Expr ::= NOT Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new NotNode(e1); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // Expr ::= ID 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IdNode(attrib); /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // Expr ::= FunCall 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib; /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // Expr ::= Constant 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib; /*System.out.println(RESULT);*/ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
