
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione4;

import java_cup.runtime.*;
import java.util.ArrayList;
import esercitazione4.ast.IdNode;
import esercitazione4.ast.ExprOpNode;
import esercitazione4.ast.Constants.*;
import esercitazione4.ast.ArithOp.*;
import esercitazione4.ast.BoolOp.*;
import esercitazione4.ast.RelOp.*;
import esercitazione4.ast.FunCallNode;
import esercitazione4.ast.ProgramNode;
import esercitazione4.ast.DeclOpNode;
import esercitazione4.ast.DefDeclOp.DefDeclNode;
import esercitazione4.ast.ParDeclOp.*;
import esercitazione4.ast.BodyNode;
import esercitazione4.ast.StatOp.*;
import esercitazione4.ast.Type;
import esercitazione4.ast.VarDeclOp.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\110\000\002\002\010\000\002\002\004\000\002\023" +
    "\004\000\002\023\004\000\002\023\002\000\002\025\004" +
    "\000\002\025\002\000\002\022\006\000\002\031\005\000" +
    "\002\031\007\000\002\031\003\000\002\031\005\000\002" +
    "\015\003\000\002\015\003\000\002\017\003\000\002\017" +
    "\003\000\002\017\003\000\002\017\003\000\002\017\003" +
    "\000\002\016\003\000\002\016\003\000\002\016\003\000" +
    "\002\016\003\000\002\016\003\000\002\016\003\000\002" +
    "\021\011\000\002\021\010\000\002\024\005\000\002\024" +
    "\003\000\002\020\005\000\002\030\005\000\002\030\003" +
    "\000\002\027\003\000\002\027\004\000\002\014\004\000" +
    "\002\014\002\000\002\010\006\000\002\011\004\000\002" +
    "\011\002\000\002\007\005\000\002\007\005\000\002\007" +
    "\005\000\002\007\006\000\002\007\004\000\002\007\012" +
    "\000\002\007\010\000\002\007\010\000\002\007\005\000" +
    "\002\026\005\000\002\026\003\000\002\012\005\000\002" +
    "\012\003\000\002\013\006\000\002\013\005\000\002\006" +
    "\005\000\002\006\005\000\002\006\005\000\002\006\005" +
    "\000\002\006\005\000\002\006\005\000\002\006\005\000" +
    "\002\006\005\000\002\006\005\000\002\006\005\000\002" +
    "\006\005\000\002\006\005\000\002\006\005\000\002\006" +
    "\004\000\002\006\004\000\002\006\003\000\002\006\003" +
    "\000\002\006\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\222\000\004\021\005\001\002\000\004\002\224\001" +
    "\002\000\010\013\011\022\ufffd\062\006\001\002\000\010" +
    "\054\223\060\ufff7\061\116\001\002\000\004\060\216\001" +
    "\002\000\010\013\011\022\ufffd\062\006\001\002\000\004" +
    "\062\161\001\002\000\004\022\015\001\002\000\010\013" +
    "\011\022\ufffd\062\006\001\002\000\004\022\ufffe\001\002" +
    "\000\036\004\ufffb\007\ufffb\011\ufffb\023\ufffb\024\ufffb\025" +
    "\ufffb\026\ufffb\027\ufffb\030\ufffb\031\ufffb\033\ufffb\041\ufffb" +
    "\050\ufffb\062\ufffb\001\002\000\036\004\031\007\023\011" +
    "\026\023\uffdb\024\030\025\037\026\034\027\021\030\043" +
    "\031\017\033\036\041\025\050\042\062\033\001\002\000" +
    "\050\032\uffe9\033\uffe9\034\uffe9\035\uffe9\037\uffe9\040\uffe9" +
    "\042\uffe9\043\uffe9\044\uffe9\045\uffe9\046\uffe9\047\uffe9\051" +
    "\uffe9\054\uffe9\055\uffe9\056\uffe9\060\uffe9\064\uffe9\065\uffe9" +
    "\001\002\000\040\004\031\007\023\011\026\023\uffdb\024" +
    "\030\025\037\026\034\027\021\030\043\031\017\033\036" +
    "\041\025\050\042\053\uffdb\062\156\001\002\000\050\032" +
    "\uffeb\033\uffeb\034\uffeb\035\uffeb\037\uffeb\040\uffeb\042\uffeb" +
    "\043\uffeb\044\uffeb\045\uffeb\046\uffeb\047\uffeb\051\uffeb\054" +
    "\uffeb\055\uffeb\056\uffeb\060\uffeb\064\uffeb\065\uffeb\001\002" +
    "\000\050\032\uffba\033\uffba\034\uffba\035\uffba\037\uffba\040" +
    "\uffba\042\uffba\043\uffba\044\uffba\045\uffba\046\uffba\047\uffba" +
    "\051\uffba\054\uffba\055\uffba\056\uffba\060\uffba\064\uffba\065" +
    "\uffba\001\002\000\004\050\150\001\002\000\004\023\147" +
    "\001\002\000\026\024\030\025\037\026\034\027\021\030" +
    "\043\031\017\033\036\041\025\050\042\062\046\001\002" +
    "\000\026\024\030\025\037\026\034\027\021\030\043\031" +
    "\017\033\036\041\025\050\042\062\046\001\002\000\042" +
    "\032\uffbb\033\uffbb\034\uffbb\035\uffbb\037\uffbb\040\uffbb\042" +
    "\uffbb\043\uffbb\044\uffbb\045\uffbb\046\uffbb\047\uffbb\055\uffbb" +
    "\056\143\064\uffbb\065\uffbb\001\002\000\050\032\uffee\033" +
    "\uffee\034\uffee\035\uffee\037\uffee\040\uffee\042\uffee\043\uffee" +
    "\044\uffee\045\uffee\046\uffee\047\uffee\051\uffee\054\uffee\055" +
    "\uffee\056\uffee\060\uffee\064\uffee\065\uffee\001\002\000\004" +
    "\050\130\001\002\000\044\032\057\033\053\034\063\035" +
    "\061\037\054\040\067\042\062\043\055\044\066\045\060" +
    "\046\056\047\065\051\uffce\055\126\056\uffce\064\uffce\065" +
    "\uffce\001\002\000\054\032\uffbc\033\uffbc\034\uffbc\035\uffbc" +
    "\037\uffbc\040\uffbc\042\uffbc\043\uffbc\044\uffbc\045\uffbc\046" +
    "\uffbc\047\uffbc\050\047\054\117\055\uffbc\057\uffd0\060\ufff7" +
    "\061\116\063\uffd0\064\uffbc\065\uffbc\001\002\000\050\032" +
    "\uffec\033\uffec\034\uffec\035\uffec\037\uffec\040\uffec\042\uffec" +
    "\043\uffec\044\uffec\045\uffec\046\uffec\047\uffec\051\uffec\054" +
    "\uffec\055\uffec\056\uffec\060\uffec\064\uffec\065\uffec\001\002" +
    "\000\040\004\ufffc\007\ufffc\011\ufffc\023\ufffc\024\ufffc\025" +
    "\ufffc\026\ufffc\027\ufffc\030\ufffc\031\ufffc\033\ufffc\041\ufffc" +
    "\050\ufffc\053\ufffc\062\ufffc\001\002\000\026\024\030\025" +
    "\037\026\034\027\021\030\043\031\017\033\036\041\025" +
    "\050\042\062\046\001\002\000\050\032\uffed\033\uffed\034" +
    "\uffed\035\uffed\037\uffed\040\uffed\042\uffed\043\uffed\044\uffed" +
    "\045\uffed\046\uffed\047\uffed\051\uffed\054\uffed\055\uffed\056" +
    "\uffed\060\uffed\064\uffed\065\uffed\001\002\000\006\064\111" +
    "\065\112\001\002\000\006\057\105\063\104\001\002\000" +
    "\026\024\030\025\037\026\034\027\021\030\043\031\017" +
    "\033\036\041\025\050\042\062\046\001\002\000\050\032" +
    "\uffea\033\uffea\034\uffea\035\uffea\037\uffea\040\uffea\042\uffea" +
    "\043\uffea\044\uffea\045\uffea\046\uffea\047\uffea\051\uffea\054" +
    "\uffea\055\uffea\056\uffea\060\uffea\064\uffea\065\uffea\001\002" +
    "\000\034\032\057\033\053\034\063\035\061\037\054\040" +
    "\067\042\062\043\055\044\066\045\060\046\056\047\065" +
    "\051\064\001\002\000\050\032\uffbb\033\uffbb\034\uffbb\035" +
    "\uffbb\037\uffbb\040\uffbb\042\uffbb\043\uffbb\044\uffbb\045\uffbb" +
    "\046\uffbb\047\uffbb\051\uffbb\054\uffbb\055\uffbb\056\uffbb\060" +
    "\uffbb\064\uffbb\065\uffbb\001\002\000\052\032\uffbc\033\uffbc" +
    "\034\uffbc\035\uffbc\037\uffbc\040\uffbc\042\uffbc\043\uffbc\044" +
    "\uffbc\045\uffbc\046\uffbc\047\uffbc\050\047\051\uffbc\054\uffbc" +
    "\055\uffbc\056\uffbc\060\uffbc\064\uffbc\065\uffbc\001\002\000" +
    "\030\024\030\025\037\026\034\027\021\030\043\031\017" +
    "\033\036\041\025\050\042\051\051\062\046\001\002\000" +
    "\004\051\052\001\002\000\050\032\uffcc\033\uffcc\034\uffcc" +
    "\035\uffcc\037\uffcc\040\uffcc\042\uffcc\043\uffcc\044\uffcc\045" +
    "\uffcc\046\uffcc\047\uffcc\051\uffcc\054\uffcc\055\uffcc\056\uffcc" +
    "\060\uffcc\064\uffcc\065\uffcc\001\002\000\050\032\uffcd\033" +
    "\uffcd\034\uffcd\035\uffcd\037\uffcd\040\uffcd\042\uffcd\043\uffcd" +
    "\044\uffcd\045\uffcd\046\uffcd\047\uffcd\051\uffcd\054\uffcd\055" +
    "\uffcd\056\uffcd\060\uffcd\064\uffcd\065\uffcd\001\002\000\026" +
    "\024\030\025\037\026\034\027\021\030\043\031\017\033" +
    "\036\041\025\050\042\062\046\001\002\000\026\024\030" +
    "\025\037\026\034\027\021\030\043\031\017\033\036\041" +
    "\025\050\042\062\046\001\002\000\026\024\030\025\037" +
    "\026\034\027\021\030\043\031\017\033\036\041\025\050" +
    "\042\062\046\001\002\000\026\024\030\025\037\026\034" +
    "\027\021\030\043\031\017\033\036\041\025\050\042\062" +
    "\046\001\002\000\026\024\030\025\037\026\034\027\021" +
    "\030\043\031\017\033\036\041\025\050\042\062\046\001" +
    "\002\000\026\024\030\025\037\026\034\027\021\030\043" +
    "\031\017\033\036\041\025\050\042\062\046\001\002\000" +
    "\026\024\030\025\037\026\034\027\021\030\043\031\017" +
    "\033\036\041\025\050\042\062\046\001\002\000\026\024" +
    "\030\025\037\026\034\027\021\030\043\031\017\033\036" +
    "\041\025\050\042\062\046\001\002\000\026\024\030\025" +
    "\037\026\034\027\021\030\043\031\017\033\036\041\025" +
    "\050\042\062\046\001\002\000\050\032\uffbf\033\uffbf\034" +
    "\uffbf\035\uffbf\037\uffbf\040\uffbf\042\uffbf\043\uffbf\044\uffbf" +
    "\045\uffbf\046\uffbf\047\uffbf\051\uffbf\054\uffbf\055\uffbf\056" +
    "\uffbf\060\uffbf\064\uffbf\065\uffbf\001\002\000\026\024\030" +
    "\025\037\026\034\027\021\030\043\031\017\033\036\041" +
    "\025\050\042\062\046\001\002\000\026\024\030\025\037" +
    "\026\034\027\021\030\043\031\017\033\036\041\025\050" +
    "\042\062\046\001\002\000\026\024\030\025\037\026\034" +
    "\027\021\030\043\031\017\033\036\041\025\050\042\062" +
    "\046\001\002\000\050\032\057\033\053\034\063\035\061" +
    "\037\054\040\uffc6\042\062\043\055\044\066\045\060\046" +
    "\056\047\065\051\uffc6\054\uffc6\055\uffc6\056\uffc6\060\uffc6" +
    "\064\uffc6\065\uffc6\001\002\000\050\032\057\033\053\034" +
    "\063\035\061\037\uffc3\040\uffc3\042\uffc3\043\uffc3\044\uffc3" +
    "\045\uffc3\046\uffc3\047\uffc3\051\uffc3\054\uffc3\055\uffc3\056" +
    "\uffc3\060\uffc3\064\uffc3\065\uffc3\001\002\000\050\032\057" +
    "\033\053\034\063\035\061\037\uffc0\040\uffc0\042\uffc0\043" +
    "\uffc0\044\uffc0\045\uffc0\046\uffc0\047\uffc0\051\uffc0\054\uffc0" +
    "\055\uffc0\056\uffc0\060\uffc0\064\uffc0\065\uffc0\001\002\000" +
    "\050\032\uffc9\033\uffc9\034\uffc9\035\uffc9\037\uffc9\040\uffc9" +
    "\042\uffc9\043\uffc9\044\uffc9\045\uffc9\046\uffc9\047\uffc9\051" +
    "\uffc9\054\uffc9\055\uffc9\056\uffc9\060\uffc9\064\uffc9\065\uffc9" +
    "\001\002\000\050\032\057\033\053\034\063\035\061\037" +
    "\uffc5\040\uffc5\042\uffc5\043\uffc5\044\uffc5\045\uffc5\046\uffc5" +
    "\047\uffc5\051\uffc5\054\uffc5\055\uffc5\056\uffc5\060\uffc5\064" +
    "\uffc5\065\uffc5\001\002\000\050\032\uffc8\033\uffc8\034\uffc8" +
    "\035\uffc8\037\uffc8\040\uffc8\042\uffc8\043\uffc8\044\uffc8\045" +
    "\uffc8\046\uffc8\047\uffc8\051\uffc8\054\uffc8\055\uffc8\056\uffc8" +
    "\060\uffc8\064\uffc8\065\uffc8\001\002\000\050\032\057\033" +
    "\053\034\063\035\061\037\uffc2\040\uffc2\042\uffc2\043\uffc2" +
    "\044\uffc2\045\uffc2\046\uffc2\047\uffc2\051\uffc2\054\uffc2\055" +
    "\uffc2\056\uffc2\060\uffc2\064\uffc2\065\uffc2\001\002\000\050" +
    "\032\uffcb\033\uffcb\034\063\035\061\037\uffcb\040\uffcb\042" +
    "\uffcb\043\uffcb\044\uffcb\045\uffcb\046\uffcb\047\uffcb\051\uffcb" +
    "\054\uffcb\055\uffcb\056\uffcb\060\uffcb\064\uffcb\065\uffcb\001" +
    "\002\000\050\032\057\033\053\034\063\035\061\037\uffc1" +
    "\040\uffc1\042\uffc1\043\uffc1\044\uffc1\045\uffc1\046\uffc1\047" +
    "\uffc1\051\uffc1\054\uffc1\055\uffc1\056\uffc1\060\uffc1\064\uffc1" +
    "\065\uffc1\001\002\000\050\032\057\033\053\034\063\035" +
    "\061\037\uffc4\040\uffc4\042\uffc4\043\uffc4\044\uffc4\045\uffc4" +
    "\046\uffc4\047\uffc4\051\uffc4\054\uffc4\055\uffc4\056\uffc4\060" +
    "\uffc4\064\uffc4\065\uffc4\001\002\000\050\032\057\033\053" +
    "\034\063\035\061\037\uffc7\040\uffc7\042\062\043\055\044" +
    "\066\045\060\046\056\047\065\051\uffc7\054\uffc7\055\uffc7" +
    "\056\uffc7\060\uffc7\064\uffc7\065\uffc7\001\002\000\050\032" +
    "\uffca\033\uffca\034\063\035\061\037\uffca\040\uffca\042\uffca" +
    "\043\uffca\044\uffca\045\uffca\046\uffca\047\uffca\051\uffca\054" +
    "\uffca\055\uffca\056\uffca\060\uffca\064\uffca\065\uffca\001\002" +
    "\000\004\056\110\001\002\000\026\024\030\025\037\026" +
    "\034\027\021\030\043\031\017\033\036\041\025\050\042" +
    "\062\046\001\002\000\004\056\107\001\002\000\040\004" +
    "\uffd7\007\uffd7\011\uffd7\023\uffd7\024\uffd7\025\uffd7\026\uffd7" +
    "\027\uffd7\030\uffd7\031\uffd7\033\uffd7\041\uffd7\050\uffd7\053" +
    "\uffd7\062\uffd7\001\002\000\040\004\uffda\007\uffda\011\uffda" +
    "\023\uffda\024\uffda\025\uffda\026\uffda\027\uffda\030\uffda\031" +
    "\uffda\033\uffda\041\uffda\050\uffda\053\uffda\062\uffda\001\002" +
    "\000\004\056\114\001\002\000\004\056\113\001\002\000" +
    "\040\004\uffd8\007\uffd8\011\uffd8\023\uffd8\024\uffd8\025\uffd8" +
    "\026\uffd8\027\uffd8\030\uffd8\031\uffd8\033\uffd8\041\uffd8\050" +
    "\uffd8\053\uffd8\062\uffd8\001\002\000\040\004\uffd9\007\uffd9" +
    "\011\uffd9\023\uffd9\024\uffd9\025\uffd9\026\uffd9\027\uffd9\030" +
    "\uffd9\031\uffd9\033\uffd9\041\uffd9\050\uffd9\053\uffd9\062\uffd9" +
    "\001\002\000\050\032\uffbe\033\uffbe\034\uffbe\035\uffbe\037" +
    "\uffbe\040\uffbe\042\uffbe\043\uffbe\044\uffbe\045\uffbe\046\uffbe" +
    "\047\uffbe\051\uffbe\054\uffbe\055\uffbe\056\uffbe\060\uffbe\064" +
    "\uffbe\065\uffbe\001\002\000\026\024\030\025\037\026\034" +
    "\027\021\030\043\031\017\033\036\041\025\050\042\062" +
    "\046\001\002\000\004\062\120\001\002\000\014\054\117" +
    "\057\uffd0\060\ufff7\061\116\063\uffd0\001\002\000\004\060" +
    "\ufff9\001\002\000\006\057\uffd1\063\uffd1\001\002\000\036" +
    "\032\057\033\053\034\063\035\061\037\054\040\067\042" +
    "\062\043\055\044\066\045\060\046\056\047\065\054\124" +
    "\060\ufff6\001\002\000\004\062\006\001\002\000\004\060" +
    "\ufff8\001\002\000\026\024\030\025\037\026\034\027\021" +
    "\030\043\031\017\033\036\041\025\050\042\062\046\001" +
    "\002\000\012\051\uffcf\056\uffcf\064\uffcf\065\uffcf\001\002" +
    "\000\026\024\030\025\037\026\034\027\021\030\043\031" +
    "\017\033\036\041\025\050\042\062\046\001\002\000\034" +
    "\032\057\033\053\034\063\035\061\037\054\040\067\042" +
    "\062\043\055\044\066\045\060\046\056\047\065\051\132" +
    "\001\002\000\004\005\133\001\002\000\004\052\134\001" +
    "\002\000\036\004\ufffb\007\ufffb\011\ufffb\024\ufffb\025\ufffb" +
    "\026\ufffb\027\ufffb\030\ufffb\031\ufffb\033\ufffb\041\ufffb\050" +
    "\ufffb\053\ufffb\062\ufffb\001\002\000\042\004\uffd4\006\136" +
    "\007\uffd4\011\uffd4\023\uffd4\024\uffd4\025\uffd4\026\uffd4\027" +
    "\uffd4\030\uffd4\031\uffd4\033\uffd4\041\uffd4\050\uffd4\053\uffd4" +
    "\062\uffd4\001\002\000\004\052\134\001\002\000\040\004" +
    "\uffd5\007\uffd5\011\uffd5\023\uffd5\024\uffd5\025\uffd5\026\uffd5" +
    "\027\uffd5\030\uffd5\031\uffd5\033\uffd5\041\uffd5\050\uffd5\053" +
    "\uffd5\062\uffd5\001\002\000\036\004\031\007\023\011\026" +
    "\024\030\025\037\026\034\027\021\030\043\031\017\033" +
    "\036\041\025\050\042\053\uffdb\062\033\001\002\000\004" +
    "\053\142\001\002\000\046\004\uffdd\006\uffdd\007\uffdd\011" +
    "\uffdd\013\uffdd\022\uffdd\023\uffdd\024\uffdd\025\uffdd\026\uffdd" +
    "\027\uffdd\030\uffdd\031\uffdd\033\uffdd\041\uffdd\050\uffdd\053" +
    "\uffdd\062\uffdd\001\002\000\040\004\uffd6\007\uffd6\011\uffd6" +
    "\023\uffd6\024\uffd6\025\uffd6\026\uffd6\027\uffd6\030\uffd6\031" +
    "\uffd6\033\uffd6\041\uffd6\050\uffd6\053\uffd6\062\uffd6\001\002" +
    "\000\034\032\057\033\053\034\063\035\061\037\054\040" +
    "\067\042\062\043\055\044\066\045\060\046\056\047\065" +
    "\056\145\001\002\000\040\004\uffd2\007\uffd2\011\uffd2\023" +
    "\uffd2\024\uffd2\025\uffd2\026\uffd2\027\uffd2\030\uffd2\031\uffd2" +
    "\033\uffd2\041\uffd2\050\uffd2\053\uffd2\062\uffd2\001\002\000" +
    "\050\032\057\033\053\034\063\035\061\037\uffbd\040\uffbd" +
    "\042\062\043\055\044\066\045\060\046\056\047\065\051" +
    "\uffbd\054\uffbd\055\uffbd\056\uffbd\060\uffbd\064\uffbd\065\uffbd" +
    "\001\002\000\004\002\001\001\002\000\026\024\030\025" +
    "\037\026\034\027\021\030\043\031\017\033\036\041\025" +
    "\050\042\062\046\001\002\000\034\032\057\033\053\034" +
    "\063\035\061\037\054\040\067\042\062\043\055\044\066" +
    "\045\060\046\056\047\065\051\152\001\002\000\004\010" +
    "\153\001\002\000\004\052\134\001\002\000\040\004\uffd3" +
    "\007\uffd3\011\uffd3\023\uffd3\024\uffd3\025\uffd3\026\uffd3\027" +
    "\uffd3\030\uffd3\031\uffd3\033\uffd3\041\uffd3\050\uffd3\053\uffd3" +
    "\062\uffd3\001\002\000\006\023\uffdc\053\uffdc\001\002\000" +
    "\050\032\uffbc\033\uffbc\034\uffbc\035\uffbc\037\uffbc\040\uffbc" +
    "\042\uffbc\043\uffbc\044\uffbc\045\uffbc\046\uffbc\047\uffbc\050" +
    "\047\054\157\055\uffbc\057\uffd0\063\uffd0\064\uffbc\065\uffbc" +
    "\001\002\000\004\062\160\001\002\000\010\054\157\057" +
    "\uffd0\063\uffd0\001\002\000\004\050\162\001\002\000\010" +
    "\012\166\051\170\062\163\001\002\000\006\055\uffe1\060" +
    "\uffe1\001\002\000\004\060\213\001\002\000\006\055\211" +
    "\060\uffe2\001\002\000\004\062\210\001\002\000\004\051" +
    "\205\001\002\000\006\052\uffde\060\174\001\002\000\006" +
    "\051\uffe5\056\172\001\002\000\006\012\166\062\163\001" +
    "\002\000\004\051\uffe6\001\002\000\014\014\204\015\202" +
    "\016\201\017\177\020\203\001\002\000\004\052\134\001" +
    "\002\000\010\013\uffe7\022\uffe7\062\uffe7\001\002\000\010" +
    "\051\ufff0\052\ufff0\056\ufff0\001\002\000\004\052\uffdf\001" +
    "\002\000\010\051\ufff1\052\ufff1\056\ufff1\001\002\000\010" +
    "\051\ufff2\052\ufff2\056\ufff2\001\002\000\010\051\uffef\052" +
    "\uffef\056\uffef\001\002\000\010\051\ufff3\052\ufff3\056\ufff3" +
    "\001\002\000\006\052\uffde\060\174\001\002\000\004\052" +
    "\134\001\002\000\010\013\uffe8\022\uffe8\062\uffe8\001\002" +
    "\000\006\055\uffe0\060\uffe0\001\002\000\006\012\166\062" +
    "\163\001\002\000\004\060\uffe3\001\002\000\014\014\204" +
    "\015\202\016\201\017\177\020\203\001\002\000\006\051" +
    "\uffe4\056\uffe4\001\002\000\004\022\uffff\001\002\000\030" +
    "\014\204\015\202\016\201\017\177\020\203\024\030\025" +
    "\037\026\034\027\021\030\043\031\017\001\002\000\004" +
    "\056\ufff5\001\002\000\004\056\222\001\002\000\004\056" +
    "\ufff4\001\002\000\044\004\ufffa\007\ufffa\011\ufffa\013\ufffa" +
    "\022\ufffa\023\ufffa\024\ufffa\025\ufffa\026\ufffa\027\ufffa\030" +
    "\ufffa\031\ufffa\033\ufffa\041\ufffa\050\ufffa\053\ufffa\062\ufffa" +
    "\001\002\000\004\062\006\001\002\000\004\002\000\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\222\000\004\002\003\001\001\000\002\001\001\000" +
    "\012\021\012\022\007\023\011\031\006\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\021\012\022\007\023" +
    "\214\031\006\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\021\012\022\007\023\013\031\006\001\001\000" +
    "\002\001\001\000\004\025\015\001\001\000\024\006\031" +
    "\007\017\011\023\012\037\013\026\016\021\022\034\026" +
    "\040\031\006\001\001\000\002\001\001\000\020\006\031" +
    "\007\017\011\154\012\037\013\026\016\021\026\040\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\006\145\013\044\016\021\001" +
    "\001\000\010\006\143\013\044\016\021\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\006\114\013\044\016\021\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\006\043" +
    "\013\044\016\021\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\006\031" +
    "\012\047\013\044\016\021\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\006\102\013\044" +
    "\016\021\001\001\000\010\006\101\013\044\016\021\001" +
    "\001\000\010\006\100\013\044\016\021\001\001\000\010" +
    "\006\077\013\044\016\021\001\001\000\010\006\076\013" +
    "\044\016\021\001\001\000\010\006\075\013\044\016\021" +
    "\001\001\000\010\006\074\013\044\016\021\001\001\000" +
    "\010\006\073\013\044\016\021\001\001\000\010\006\072" +
    "\013\044\016\021\001\001\000\002\001\001\000\010\006" +
    "\071\013\044\016\021\001\001\000\010\006\070\013\044" +
    "\016\021\001\001\000\010\006\067\013\044\016\021\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\006\031\012\105\013\044\016\021\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\006\122\013\044\016" +
    "\021\001\001\000\006\026\121\031\120\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\031\124\001\001\000\002\001\001\000\012" +
    "\006\031\012\126\013\044\016\021\001\001\000\002\001" +
    "\001\000\010\006\130\013\044\016\021\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\010\134\001\001\000" +
    "\004\025\137\001\001\000\002\001\001\000\004\010\136" +
    "\001\001\000\002\001\001\000\024\006\031\007\017\011" +
    "\140\012\037\013\026\016\021\022\034\026\040\031\006" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\006\150\013\044\016\021\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\010\153" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\026\121\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\020\170\024\166\027\164\030\163\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\014\174\001" +
    "\001\000\002\001\001\000\012\020\170\024\172\027\164" +
    "\030\163\001\001\000\002\001\001\000\004\017\177\001" +
    "\001\000\004\010\175\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\205" +
    "\001\001\000\004\010\206\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\027\164\030\211\001\001\000\002" +
    "\001\001\000\004\017\213\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\015\217\016\220\017\216\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\031\120\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Programma ::= PROGRAM Decls BEGIN VarDecls Statements END 
            {
              Object RESULT =null;
		int declsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int declsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		ArrayList<DeclOpNode> decls = (ArrayList<DeclOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<VarDeclNode> vars = (ArrayList<VarDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int statsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int statsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<StatOpNode> stats = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ProgramNode(decls, vars, stats);
                                                                              System.out.println(RESULT);
                                                                           
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Programma",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Programma EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Decls ::= VarDecl Decls 
            {
              ArrayList<DeclOpNode> RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object var = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<DeclOpNode> list = (ArrayList<DeclOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(0, (VarDeclNode) var);
                                    RESULT = list;
                                    System.out.println("VarDecls Fittizio: " + RESULT);
                                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Decls",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // Decls ::= DefDecl Decls 
            {
              ArrayList<DeclOpNode> RESULT =null;
		int defleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int defright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object def = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<DeclOpNode> list = (ArrayList<DeclOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(0, (DefDeclNode) def);
                                  RESULT = list;
                                  System.out.println("DefDecls Fittizio: " + RESULT);
                               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Decls",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Decls ::= 
            {
              ArrayList<DeclOpNode> RESULT =null;
		 ArrayList<DeclOpNode> list = new ArrayList<>();
                       RESULT = list;
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Decls",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // VarDecls ::= VarDecls VarDecl 
            {
              ArrayList<VarDeclNode> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<VarDeclNode> list = (ArrayList<VarDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object var = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((VarDeclNode) var);
                                          RESULT = list;
                                          //System.out.println("VarDecls Fittizio: " + RESULT);
                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarDecls",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // VarDecls ::= 
            {
              ArrayList<VarDeclNode> RESULT =null;
		 ArrayList<VarDeclNode> list = new ArrayList<>();
                         RESULT = list;
                      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarDecls",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // VarDecl ::= VarsOptInit COLON TypeOrConstant SEMI 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<VarOptInitNode> vars = (ArrayList<VarOptInitNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int typeOrConstantleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeOrConstantright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object typeOrConstant = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new VarDeclNode(vars, typeOrConstant); System.out.println(RESULT);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarDecl",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // VarsOptInit ::= ID PIPE VarsOptInit 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<VarOptInitNode> list = (ArrayList<VarOptInitNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(new VarOptInitNode(new IdNode(attrib)));
                                                   RESULT = list;
                                                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // VarsOptInit ::= ID ASSIGNDECL Expr PIPE VarsOptInit 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<VarOptInitNode> list = (ArrayList<VarOptInitNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(new VarOptInitNode(new IdNode(id), expr));
                                                                  RESULT = list;
                                                                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // VarsOptInit ::= ID 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<VarOptInitNode> list = new ArrayList<>();
                           list.add(new VarOptInitNode(new IdNode(attrib)));
                           RESULT = list;
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // VarsOptInit ::= ID ASSIGNDECL Expr 
            {
              ArrayList<VarOptInitNode> RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<VarOptInitNode> list = new ArrayList<>();
                                            list.add(new VarOptInitNode(new IdNode(id), expr));
                                            RESULT = list;
                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VarsOptInit",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // TypeOrConstant ::= Type 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib;  System.out.println("Type Fittizio: " + RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TypeOrConstant",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // TypeOrConstant ::= Constant 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib; System.out.println("Constant Fittizio: " + RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("TypeOrConstant",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Type ::= INT 
            {
              Object RESULT =null;
		 RESULT = Type.INT; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Type ::= BOOL 
            {
              Object RESULT =null;
		 RESULT = Type.BOOL; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // Type ::= DOUBLE 
            {
              Object RESULT =null;
		 RESULT = Type.DOUBLE; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Type ::= STRING 
            {
              Object RESULT =null;
		 RESULT = Type.STRING; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Type ::= CHAR 
            {
              Object RESULT =null;
		 RESULT = Type.CHAR; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Constant ::= TRUE 
            {
              Object RESULT =null;
		 RESULT = new BoolNode(true); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Constant ::= FALSE 
            {
              Object RESULT =null;
		 RESULT = new BoolNode(false); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Constant ::= INT_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IntNode((int) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Constant ::= DOUBLE_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DoubleNode((double) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Constant ::= CHAR_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CharNode((char) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Constant ::= STRING_CONST 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new StringNode((String) attrib); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // DefDecl ::= DEF ID LPAR ParDecls RPAR OptType Body 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int paramsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int paramsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<ParDeclNode> params = (ArrayList<ParDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DefDeclNode(new IdNode(name), params, type, body);
                                                                            System.out.println(RESULT);
                                                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DefDecl",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // DefDecl ::= DEF ID LPAR RPAR OptType Body 
            {
              Object RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DefDeclNode(new IdNode(name), type, body);
                                                          System.out.println(RESULT);
                                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DefDecl",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ParDecls ::= ParDecl SEMI ParDecls 
            {
              ArrayList<ParDeclNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<ParDeclNode> list = (ArrayList<ParDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((ParDeclNode) attrib);
                                                  RESULT = list;
                                                  System.out.println("ParDecls fittizio: " + RESULT);
                                               
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ParDecls",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ParDecls ::= ParDecl 
            {
              ArrayList<ParDeclNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<ParDeclNode> list = new ArrayList<>();
                             list.add((ParDeclNode) attrib);
                             RESULT = list;
                             System.out.println("ParDecls fittizio: " + RESULT);
                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ParDecls",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ParDecl ::= PVars COLON Type 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<PVarNode> vars = (ArrayList<PVarNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new ParDeclNode(vars, type);
                                          System.out.println(RESULT);
                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ParDecl",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // PVars ::= PVar COMMA PVars 
            {
              ArrayList<PVarNode> RESULT =null;
		int pvarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int pvarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object pvar = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<PVarNode> list = (ArrayList<PVarNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((PVarNode) pvar);
                                        RESULT = list;
                                        //System.out.println("PVars fittizio: " + RESULT);
                                     
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVars",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // PVars ::= PVar 
            {
              ArrayList<PVarNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<PVarNode> list = new ArrayList<>();
                       list.add((PVarNode) attrib);
                       RESULT = list;
                       //System.out.println("PVar fittizio: " + RESULT);
                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVars",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // PVar ::= ID 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new PVarNode(new IdNode(attrib)); System.out.println(RESULT);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVar",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // PVar ::= REF ID 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new PVarNode(new IdNode(attrib), true); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("PVar",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // OptType ::= COLON Type 
            {
              Object RESULT =null;
		int typeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int typeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object type = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = type; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OptType",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // OptType ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("OptType",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Body ::= LBRAC VarDecls Statements RBRAC 
            {
              Object RESULT =null;
		int varsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int varsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<VarDeclNode> vars = (ArrayList<VarDeclNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int statsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int statsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<StatOpNode> stats = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new BodyNode(vars, stats);
                                                       System.out.println(RESULT);
                                                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Body",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Statements ::= Stat Statements 
            {
              ArrayList<StatOpNode> RESULT =null;
		int statleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int statright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object stat = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<StatOpNode> list = (ArrayList<StatOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(0, (StatOpNode) stat);
                                            RESULT = list;
                                            //System.out.println("Statements Fittizio: " + RESULT);
                                         
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Statements",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Statements ::= 
            {
              ArrayList<StatOpNode> RESULT =null;
		 ArrayList<StatOpNode> list = new ArrayList<>();
                             RESULT = list;
                          
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Statements",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Stat ::= Vars IN SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<IdNode> attrib = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new ReadOpNode(attrib); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Stat ::= Exprs OUT SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<ExprOpNode> attrib = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new WriteOpNode(attrib); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Stat ::= Exprs OUTNL SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ArrayList<ExprOpNode> attrib = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new WriteOpNode(attrib, true); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Stat ::= Vars ASSIGN Exprs SEMI 
            {
              Object RESULT =null;
		int idsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int idsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ArrayList<IdNode> ids = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int exprsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exprsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<ExprOpNode> exprs = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new AssignOpNode(ids, exprs); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Stat ::= FunCall SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = attrib; System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Stat ::= IF LPAR Expr RPAR THEN Body ELSE Body 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int body1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int body1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object body1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int body2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int body2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IfThenElseNode(expr, body1, body2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Stat ::= IF LPAR Expr RPAR THEN Body 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IfThenNode(expr, body); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Stat ::= WHILE LPAR Expr RPAR DO Body 
            {
              Object RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Object expr = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object body = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new WhileNode(expr, body); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Stat ::= RETURN Expr SEMI 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ReturnOpNode(attrib); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Stat",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Vars ::= ID PIPE Vars 
            {
              ArrayList<IdNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<IdNode> list = (ArrayList<IdNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add(new IdNode(attrib));
                                     RESULT = list;
                                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Vars",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // Vars ::= ID 
            {
              ArrayList<IdNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<IdNode> list = new ArrayList<>();
                    list.add(new IdNode(attrib));
                    RESULT = list;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Vars",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Exprs ::= Expr COMMA Exprs 
            {
              ArrayList<ExprOpNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int listleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int listright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ArrayList<ExprOpNode> list = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 list.add((ExprOpNode) attrib);
                                          RESULT = list;
                                          System.out.println("Exprs Fittizio: " + RESULT);
                                       
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exprs",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Exprs ::= Expr 
            {
              ArrayList<ExprOpNode> RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 ArrayList<ExprOpNode> list = new ArrayList<>();
                       list.add((ExprOpNode) attrib);
                       RESULT = list;
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Exprs",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // FunCall ::= ID LPAR Exprs RPAR 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int refleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int refright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ArrayList<ExprOpNode> ref = (ArrayList<ExprOpNode>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new FunCallNode(new IdNode (attrib), ref);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FunCall",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // FunCall ::= ID LPAR RPAR 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new FunCallNode(new IdNode (attrib)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("FunCall",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // Expr ::= Expr PLUS Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AddNode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // Expr ::= Expr MINUS Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DiffNode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // Expr ::= Expr TIMES Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new MulNode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // Expr ::= Expr DIV Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DivNode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // Expr ::= Expr AND Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AndNode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // Expr ::= Expr OR Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new OrNode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // Expr ::= Expr GT Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new GTNode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // Expr ::= Expr GE Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new GENode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // Expr ::= Expr LT Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LTNode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // Expr ::= Expr LE Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LENode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // Expr ::= Expr EQ Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new EQNode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // Expr ::= Expr NE Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new NENode(e1, e2); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // Expr ::= LPAR Expr RPAR 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e1; System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // Expr ::= MINUS Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new UMinusNode(e1); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // Expr ::= NOT Expr 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		  RESULT = new NotNode(e1); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // Expr ::= ID 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String attrib = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new IdNode(attrib); System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // Expr ::= FunCall 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib; System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // Expr ::= Constant 
            {
              Object RESULT =null;
		int attribleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int attribright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object attrib = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = attrib; System.out.println(RESULT); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expr",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
